#include "HyphaJapaneseCatalog.h"

// PRE / POST Blind: its steps, the DAW and HYPHA instructions for each one, the answers, and every
// reason it can stop. It is a Preference Listening Trial, so the answers say which source is
// preferred, never which one is better.
namespace hypha::i18n::catalog
{
namespace
{
const Entry entries[] = {
    // ローカル Blind の取り込みと live 比較の段階（2026-10-04 まで Reference の A の取り込みの区分にあった）。
    { "PLAY", u8"再生して" },
    // VERSION BLIND の操作の失敗（Blind の画面の原因と直し方の行）。役や gain の手がかりを入れない。
    { "The source did not switch", u8"ソースが切り替わりませんでした" },
    { "Keep the DAW playing and press it again", u8"DAWを再生したまま、もう一度押してください" },
    { "Both sources are not heard yet", u8"まだ両方のソースを聴いていません" },
    { "Listen to SOURCE 1 and SOURCE 2, then reveal", u8"SOURCE 1と2を聴いてから開示してください" },
    { "CAPTURING", u8"取り込み中" },
    { "WAIT", u8"待機中" },
    { "CAPTURE A", u8"Aを取り込む" },
    { "Ended; normal level returns with audio", u8"比較終了・音声処理の再開で通常音量へ" },
    { "RETURNING +%1 dB", u8"復帰待ち +%1 dB" },
    { "Waiting for comparison; POST plays", u8"比較の準備を待っています（今はPOST）" },
    { "DAW timing is unavailable for this loop", u8"このLOOPではDAWの時刻対応を確認できません" },
    { "Loop is too short for verified timing", u8"このLOOPは時刻対応を保証できる長さより短すぎます" },
    { "The PRE loop occurrence is not verified", u8"PREのどの周回に対応するか確認できません" },
    { "Loop boundary timing is not confirmed", u8"ループ境界の時刻対応を確認できません" },
    { "The loop is shorter than the verified timing range", u8"LOOPが保証済みの時刻範囲より短すぎます" },
    { "DAW timing cannot identify this loop occurrence", u8"DAWの時刻情報ではこの周回を特定できません" },
    { "POST plays; END closes comparison", u8"POSTを出力中。「終了」で比較を閉じられます" },
    { "Loop timing pending; MATCH held; POST plays", u8"ループ時刻確認中・MATCH保持（今はPOST）" },
    { "Loop too short for verified timing; POST plays", u8"LOOPが短すぎるためPOSTを出力中" },
    { "LOOP timing unverified; POST; END closes", u8"LOOP時刻未確認・POST（終了で閉じる）" },
    { "MATCH held; select PRE to check timing", u8"MATCH値を保持中・PRE選択で時刻対応を確認" },
    { "Audio gap: select PRE again (POST)", u8"音声の連続性中断・PREを再選択（POST再生）" },
    { "Clock missing: select PRE again (POST)", u8"時刻情報が中断・PREを再選択（POST再生）" },
    { "Stop/play DAW; END, then BLIND", u8"DAWを停止→再生し、終了後にBLINDへ" },
    { "Stopped: RETURN, then LISTEN (POST)", u8"中断：RETURN後にLISTEN（今はPOST）" },
    { "Comparison releasing; POST plays", u8"比較を終了処理中（今はPOST）" },
    { "Reopened: MENU > LISTEN (POST)", u8"開き直しました：MENU→LISTEN（今はPOST）" },
    { "Format changed: MENU > LISTEN (POST)", u8"形式が変わりました：MENU→LISTEN（今はPOST）" },
    { "PRE changed: check PAIR, MENU > LISTEN (POST)", u8"PRE変更：PAIR確認後MENU→LISTEN（今はPOST）" },
    { "Stopped: MENU > LISTEN (POST)", u8"止まりました：MENU→LISTEN（今はPOST）" },
    { "Play the DAW and check PRE is enabled", u8"DAWを再生し、PREが有効か確認してください" },
    { "PRE pending: check PRE is on (POST)", u8"PRE未着：PREが有効か確認（今はPOST）" },
    { "DAW playback stopped", u8"DAWの再生が停止しました" },
    { "DAW position was discontinuous", u8"DAWの再生位置が不連続になりました" },
    { "Audio callback gap detected", u8"音声処理の呼び出しに空白がありました" },
    { "DAW position unavailable", u8"DAWの再生位置を取得できません" },
    { "Audio clock unavailable", u8"音声の時計を取得できません" },
    { "PRE timing is not confirmed", u8"PREとの時刻対応を確認できません" },
    { "PRE data is being written", u8"PREの音声を書き込み中です" },
    { "PRE continuity changed", u8"PREの連続区間が変わりました" },
    { "PRE data has not arrived", u8"PREの音声が届いていません" },
    { "PRE data is no longer buffered", u8"必要なPREの音声が残っていません" },
    { "PRE data changed during reading", u8"読み取り中にPREの音声が更新されました" },
    { "PRE identity or format changed", u8"PREの識別情報か音声形式が変わりました" },
    // The status told whole: "LISTEN: <cause>. <next step>" (HyphaLiveCompareRecoveryText.h).
    { "LISTEN: %1. %2", u8"LISTEN：%1。%2" },
    { "LISTEN: %1.", u8"LISTEN：%1。" },
    { "POST plays until PRE is confirmed, then it resumes by itself.", u8"PREを確かめるまではPOST。確かめたら自動で戻ります。" },
    { "POST plays now. Play the DAW to resume.", u8"今はPOST。DAWを再生すると戻ります。" },
    { "POST plays now. Stop and play the DAW to continue.", u8"今はPOST。DAWを止めて再生し直すと続きます。" },
    { "POST plays now. Turn on the DAW's delay compensation.", u8"今はPOST。DAWの遅延補償をオンにしてください。" },
    { "POST plays now. Check the PRE in PAIR, then MENU > LISTEN.", u8"今はPOST。PAIRでPREを確かめ、MENU→LISTENで比べ直します。" },
    { "POST plays now. Check the chain's levels, then MATCH again.", u8"今はPOST。チェインの音量を確かめ、MATCHし直します。" },
    { "POST plays now. Select PRE to compare again.", u8"今はPOST。PREを選ぶと比べ直せます。" },
    { "Press END, then start BLIND again.", u8"ENDを押してから、BLINDを始め直します。" },
    { "POST is still lowered. Press RETURN, then LISTEN.", u8"POSTは下げたまま。RETURNを押してからLISTENします。" },
    { "POST plays now. MENU > LISTEN compares again.", u8"今はPOST。MENU→LISTENで比べ直せます。" },
    { "The selected PRE changed", u8"選択中のPREが変わりました" },
    { "PRE connection was lost", u8"PREとの接続が切れました" },
    { "Audio format changed", u8"音声形式が変わりました" },
    { "Plugin state was restored", u8"プラグインの状態が復元されました" },
    { "DAW delay compensation is off", u8"DAWの遅延補償が無効です" },
    { "Audio timing changed", u8"音声の時間差の推定値が変わりました" },
    { "Plugin bypass was reported", u8"DAWからバイパスの通知がありました" },
    { "Offline rendering was reported", u8"オフライン書き出しの通知がありました" },
    { "Another audition took the output", u8"別の試聴が出力を使用しました" },
    { "The fixed MATCH became invalid", u8"固定したMATCHが無効になりました" },
    { "Invalid audio samples detected", u8"不正な音声値を検出しました" },
    { "The approved level limit was exceeded", u8"承認済みの音量上限を超えました" },
    { "Audio block exceeded prepared size", u8"音声処理の単位が準備した容量を超えました" },
    { "Random assignment was unavailable", u8"ランダムな割当を準備できません" },
    { "Comparison could not be verified", u8"比較の成立を確認できません" },
    { "Stop and play the DAW to continue", u8"DAWを停止して再生すると再確認します" },
    { "Enable DAW delay compensation", u8"DAWの遅延補償を有効にしてください" },
    { "Keep playing; resumes when confirmed", u8"再生を続けると、確認後に自動で進みます" },
    { "Enable compensation; END, then BLIND", u8"遅延補償を有効にし、終了後にBLINDへ" },
    { "Check the PRE pair; END, then BLIND", u8"PREのペアを確認し、終了後にBLINDへ" },
    { "Check chain levels; END, then BLIND", u8"チェインの音量を確認し、終了後にBLINDへ" },
    { "Disable bypass; END, then BLIND", u8"バイパスを解除し、終了後にBLINDへ" },
    { "END, then start BLIND again", u8"終了してから、BLINDを始め直してください" },
    { "Timing changed: stop/play DAW (POST)", u8"時間差が変化：DAWを停止→再生（今はPOST）" },
    { "Compensation off: enable it (POST)", u8"遅延補償が無効：有効にしてください（今はPOST）" },
    { "DAW stopped: play to resume (POST)", u8"DAW停止中：再生すると復帰（今はPOST）" },
    { "Clock missing: restart playback (POST)", u8"時計が不明：DAWを停止→再生（今はPOST）" },
    { "Block too large: reduce buffer (POST)", u8"処理単位が過大：バッファを縮小（今はPOST）" },
    { "PRE changed: check pair; END (POST)", u8"PREが失効：ペア確認後に終了（今はPOST）" },
    { "Checking PRE: auto-resume; POST plays", u8"PREを確認中：確認後に自動復帰（今はPOST）" },
    { "Level limit: rematch, select PRE (POST)", u8"音量上限：再MATCH後にPRE選択（今はPOST）" },
    { "Invalid audio: check chain (POST)", u8"不正な音声：チェインを確認（今はPOST）" },
    { "Bypassed: enable, select PRE (POST)", u8"バイパス中：解除後にPRE選択（今はPOST）" },
    { "Offline: play, select PRE (POST)", u8"書き出し中：再生後にPRE選択（今はPOST）" },
    { "Other audition: end it, select PRE", u8"別の試聴が出力中：終了後にPRE選択" },
    { "Sources revealed; keep comparing", u8"対応を開示しました。そのまま比較できます" },
    { "Reveal the sources when ready", u8"聴き比べたら対応を開示できます" },
    { "Reveal the sources without an answer", u8"回答せずに音源の対応を開示します" },
    { "PREFER SOURCE 1", u8"1が好み" },
    { "PREFER SOURCE 2", u8"2が好み" },
    { "END restores normal level", u8"終了すると通常の音量に戻ります" },
    { "END returns +%1 dB", u8"終了すると音量が%1 dB上がります" },
    // VERSION BLIND（REF）を同じ画面で出す文（HyphaVersionBlindScreen.cpp）。A は Kirin OS と同じ役の名前。
    { "END returns to A", u8"終了するとAに戻ります" },
    { "Blind stopped; A plays", u8"Blindを中止しました。Aが鳴っています" },
    { "Preparing the sources; A plays", u8"準備しています。Aが鳴っています" },
    { "Play the DAW to continue", u8"DAWを再生すると続けられます" },
    { "Play within the song; A plays", u8"曲の中で再生してください。Aが鳴っています" },
    { "Blind stopped; POST output", u8"比較を中断しました。出力はPOSTです" },
    { "Blind stopped; output released", u8"比較を中断し、試聴出力を解放しました" },
    { "Returning to normal level", u8"通常の音量に戻しています" },
    { "Return waiting for audio", u8"再生すると通常音量に戻って終了します" },
    { "Lower POST to match levels?", u8"POSTを下げて音量を揃えますか？" },
    { "Lower %1 dB; END returns the same amount", u8"%1 dB下げます。終了時に同じ量だけ上がります" },
    { "Choose an answer when ready", u8"聴き比べたら回答を選んでください" },
    { "Try both sources while playing", u8"再生したまま1と2を切り替えてください" },
    { "Play the DAW to begin", u8"DAWを再生すると準備が始まります" },
    { "Matching levels; POST plays", u8"POSTを再生しながら音量を揃えています" },
    { "Choose an answer and reveal", u8"回答して正体を表示します" },
    { "Lower POST and begin Blind", u8"POSTを下げてBlindを開始します" },
    { "End and restore normal level", u8"終了して通常の音量に戻します" },
    { "LOWER POST", u8"POSTを下げる" },
    { "RETURNING", u8"復帰待ち" },
    { "End the current comparison first", u8"現在の比較を終了してください" },
    { "Match levels and compare while the song plays", u8"再生を続けたまま、音量を揃えて聴き比べます" },
    { "End listening and restore normal POST level", u8"試聴を終了してPOSTを通常の音量に戻します" },
    // The step bar and the purpose line (HyphaLocalBlindSteps.h, INV-S43).
    { "1  Capture", u8"1  取り込み" },
    { "2  Start", u8"2  開始" },
    { "3  Listen", u8"3  試聴" },
    { "4  Answer", u8"4  回答" },
    { "5  Result", u8"5  結果" },
    { "Hear the same 4 seconds of PRE and POST at matched level, without knowing which is "
      "which, and say which you prefer, if either.",
      u8"同じ4秒間のPREとPOSTを、音量を揃え、どちらがどちらか分からない状態で聴き比べます。"
      u8"好みがあれば、その方を答えます。" },
    // Steps.
    { "READY TO CAPTURE", u8"取り込み準備完了" },
    { "BEFORE CAPTURE", u8"取り込みの前に" },
    { "CAPTURING EXACT 4 SECOND RANGE", u8"同じ4秒間を取り込み中" },
    { "Keep playback running without seeking, looping, bypassing, or changing PDC.",
      u8"再生を続けてください。移動、ループ、バイパス、PDCの変更はしないでください。" },
    { "PREPARING COMPARISON", u8"比較を準備中" },
    { "The live signal remains unchanged while the fixed copies are checked.",
      u8"固定したコピーを確認する間も、今の音は変わりません。" },
    { "EXACT RANGE READY", u8"範囲の準備完了" },
    { "HYPHA: start Blind. DAW: play from before the captured range.",
      u8"HYPHA：Blindを開始します。DAW：取り込んだ範囲の少し前から再生してください。" },
    { "LOWER POST %1 dB & START", u8"POSTを%1 dB下げて開始" },
    { "Approve fixed POST attenuation and start Blind Compare",
      u8"POSTを一定量下げることを承認し、Blind Compareを開始します" },
    { "START BLIND", u8"Blindを開始" },
    // The named A/B before Blind (INV-LC17).
    { "NAMED A/B", u8"記名A/B" },
    { "LOWER POST %1 dB & A/B", u8"POSTを%1 dB下げてA/B" },
    { "Approve fixed POST attenuation and hear PRE and POST by name",
      u8"POSTを一定量下げることを承認し、PREとPOSTを名前付きで聴きます" },
    { "Hear PRE and POST by name at the fixed level before Blind",
      u8"Blindの前に、固定の音量でPREとPOSTを名前付きで聴きます" },
    { "SWITCHING TO PRE", u8"PREに切り替え中" },
    { "SWITCHING TO POST", u8"POSTに切り替え中" },
    { "PLAYING PRE", u8"PREを再生中" },
    { "PLAYING POST", u8"POSTを再生中" },
    { "DAW: play from before the captured range. Choose PRE or POST at any time.",
      u8"DAW：取り込んだ範囲の少し前から再生してください。PREとPOSTはいつでも選べます。" },
    { "Choose PRE or POST at any time. START BLIND hides which is which.",
      u8"PREとPOSTはいつでも選べます。「Blindを開始」で、どちらがどちらか分からなくなります。" },
    { "Start Blind on the same range; which is which is hidden again",
      u8"同じ範囲でBlindを始めます。どちらがどちらかは再び隠れます" },
    { "Play PRE, the input of this chain, at the fixed level",
      u8"このチェーンの入力、PREを固定の音量で再生します" },
    { "Play POST, the output of this chain", u8"このチェーンの出力、POSTを再生します" },
    { "Start the prepared comparison. PRE is matched to POST with fixed gain; DAW Solo and "
      "routing stay unchanged",
      u8"準備した比較を始めます。PREは固定のゲインでPOSTに揃えます。DAWのソロと経路は変わりません" },
    { "SOURCE 1 COMPLETE", u8"SOURCE 1 聴取完了" },
    { "SOURCE 2 READY", u8"SOURCE 2 準備完了" },
    { "WAITING FOR CAPTURED RANGE START", u8"範囲の始まりを待機中" },
    { "DAW: replay from before the captured range. No source selection is needed.",
      u8"DAW：取り込んだ範囲の少し前から、もう一度再生してください。ソースを選ぶ必要はありません。" },
    { "DAW: play from before the captured range to hear the full pass.",
      u8"DAW：取り込んだ範囲の少し前から再生して、1周を聴いてください。" },
    { "PASS COMPLETE", u8"1周完了" },
    { "SWITCHING TO SOURCE %1", u8"SOURCE %1に切り替え中" },
    { "LISTENING TO SOURCE %1", u8"SOURCE %1を再生中" },
    { "WAITING FOR AUDIBLE PLAYBACK", u8"音が出る再生を待っています" },
    { "Choose an answer to reveal, or replay a source if needed.",
      u8"回答を選ぶと答えを表示します。必要ならソースをもう一度再生できます。" },
    { "DAW: replay the captured range. The next source is selected automatically.",
      u8"DAW：取り込んだ範囲をもう一度再生してください。次のソースは自動で選ばれます。" },
    { "Listen to one complete pass of Source 1 and Source 2.",
      u8"Source 1とSource 2を、それぞれ1周ずつ最後まで聴いてください。" },
    { "%1. Select END when finished.", u8"%1。終わったら「終了」を選んでください。" },
    { ". Select END when finished.", u8"終わったら「終了」を選んでください。" },
    { "WAITING FOR LIVE OUTPUT", u8"今の音の出力を待機中" },
    { "RETURN TO LIVE", u8"今の音に戻す" },
    { "DAW: resume audio processing. Closes when Live is confirmed.",
      u8"DAW：音声処理を再開してください。今の音を確認できたら閉じます。" },
    { "Live level will rise by %1 dB.", u8"今の音のレベルが%1 dB上がります。" },
    { "Return to the unchanged live signal.", u8"変えていない今の音に戻ります。" },
    { "COMPARISON STOPPED", u8"比較を中止しました" },
    { "%1 Live +%2 dB.", u8"%1 今の音は+%2 dB戻ります。" },
    { "LIVE SIGNAL RESTORED", u8"今の音に戻りました" },
    { "The comparison is closed. Live output is restored.",
      u8"比較を閉じました。今の音の出力に戻りました。" },
    { "GAIN MATCH UNAVAILABLE", u8"Gain Matchを使えません" },
    { "COMPARISON NOT PREPARED", u8"比較を準備できません" },

    // Sources and answers.
    { "DONE", u8"完了" },
    { "PLAYING", u8"再生中" },
    { "NEXT", u8"次" },
    { "ANSWER: PREFER 1", u8"回答：1が好み" },
    { "ANSWER: PREFER 2", u8"回答：2が好み" },
    { "ANSWER: NO PREFERENCE", u8"回答：どちらでもない" },
    { "ANSWER: CANNOT TELL", u8"回答：区別できない" },
    { "NO PREF", u8"好みなし" },
    { "NO PREFERENCE", u8"どちらでもない" },
    { "CAN'T TELL", u8"区別できない" },
    { "CANNOT TELL", u8"区別できない" },
    { "BACK TO KEEP", u8"Keepに戻る" },
    { "CAPTURE AGAIN", u8"もう一度取り込む" },
    { "CAPTURE 4 S", u8"4秒を取り込む" },
    { "CLOSE", u8"閉じる" },
    { "Replay hidden source 1 (optional)", u8"隠れたソース1をもう一度再生します（任意）" },
    { "Replay hidden source 2 (optional)", u8"隠れたソース2をもう一度再生します（任意）" },
    { "Source 1 progress; selection is automatic", u8"ソース1の進み具合です。選択は自動です" },
    { "Source 2 progress; selection is automatic", u8"ソース2の進み具合です。選択は自動です" },
    { "Listen to hidden source 1", u8"隠れたソース1を聴きます" },
    { "Listen to hidden source 2", u8"隠れたソース2を聴きます" },
    { "Choose source 1 and reveal", u8"ソース1を選んで答えを表示します" },
    { "Choose source 2 and reveal", u8"ソース2を選んで答えを表示します" },
    { "Choose no preference and reveal", u8"「どちらでもない」を選んで答えを表示します" },
    { "Choose cannot tell apart and reveal", u8"「区別できない」を選んで答えを表示します" },
    { "Start the prepared comparison", u8"準備した比較を始めます" },
    { "Reveal the hidden source assignment", u8"隠れたソースの割り当てを表示します" },
    { "Capture one exact four second range", u8"同じ4秒間を取り込みます" },
    { "Resolve the capture requirement", u8"取り込みに必要な条件を整えます" },
    { "Gain Match mode for this comparison", u8"この比較のGain Matchのモード" },
    { "2MIX: continuous sections. TRACK / STEM: short or sparse events. Applies to this "
      "comparison.",
      u8"2MIX：途切れない音の区間。TRACK / STEM：短い音やまばらな音。この比較にだけ使います。" },
    { "Stop the comparison safely", u8"比較を安全に止めます" },
    { "Return explicitly to the live signal", u8"操作して今の音に戻ります" },
    { "Close Blind Compare", u8"Blind Compareを閉じます" },

    // Before a capture.
    { "DAW: play the section. HYPHA: capture 4 seconds.",
      u8"DAW：その区間を再生してください。HYPHA：4秒間を取り込みます。" },
    { "This format cannot start PRE / POST Blind.", u8"この形式ではPRE / POST Blindを始められません。" },
    { "Finish the current comparison and return to Live.",
      u8"今の比較を終えて、今の音に戻ってください。" },
    { "The previous capture is still releasing its resources.",
      u8"前の取り込みがまだ資源を解放しています。" },
    { "Choose the PRE to compare with this POST.", u8"このPOSTと比べるPREを選んでください。" },
    { "Finish the current Keep / Record before capturing.",
      u8"取り込む前に、今のKeep／Recordを終えてください。" },
    { "Finish Reference Blind and return to Live first.",
      u8"先にReferenceのBlindを終えて、今の音に戻ってください。" },
    { "Reference lowered A. Press RETURN first.", u8"ReferenceでAを下げています。先にRETURNを押してください。" },
    { "The previous audio capture is still in use.", u8"前の音声の取り込みがまだ使われています。" },
    { "DAW: start playback, then capture the section.",
      u8"DAW：再生を始めてから、その区間を取り込んでください。" },
    { "DAW sample position or format is not available for capture.",
      u8"DAWの再生位置か形式を、取り込みに使えません。" },
    { "The measurement engine is not available.", u8"計測エンジンを使えません。" },
    { "Capture could not be admitted. Check the current pair and comparisons.",
      u8"取り込みを始められませんでした。今のペアと比較を確認してください。" },
    { "The capture request could not be sent. Try again after it is released.",
      u8"取り込みの要求を送れませんでした。解放されてから、もう一度試してください。" },
    { "Capture could not start.", u8"取り込みを開始できませんでした。" },

    // Why it stopped.
    { "The selected pair changed. Return to the live signal, then capture again.",
      u8"選んだペアが変わりました。今の音に戻ってから、もう一度取り込んでください。" },
    { "The exact range could not be scheduled. Keep playback running and try again.",
      u8"同じ範囲を予約できませんでした。再生を続けたまま、もう一度試してください。" },
    { "The exact PRE and POST range was not completed.",
      u8"PREとPOSTの同じ範囲を取り込みきれませんでした。" },
    { "Capture a section where both PRE and POST contain audible events.",
      u8"PREとPOSTの両方に音がある区間を取り込んでください。" },
    { "Capture a busier section. For short sounds, choose TRACK / STEM.",
      u8"音の多い区間を取り込んでください。短い音ならTRACK / STEMを選んでください。" },
    { "The comparison could not be prepared. Capture again.",
      u8"比較を準備できませんでした。もう一度取り込んでください。" },
    { "The prepared comparison could not be made available.",
      u8"準備した比較を使える状態にできませんでした。" },
    { "The channel layout or sample rate changed.", u8"チャンネル構成かサンプルレートが変わりました。" },
    { "Playback stopped, bypassed, or entered offline render.",
      u8"再生が止まったか、バイパスされたか、オフラインのレンダリングに入りました。" },
    { "The comparison ownership changed.", u8"比較を行う側が変わりました。" },
    { "Playback jumped outside the exact captured sequence.",
      u8"再生が取り込んだ範囲の外へ移動しました。" },
    { "Playback did not begin at the captured range start.",
      u8"再生が取り込んだ範囲の始まりから始まりませんでした。" },
    { "The host clock or delay compensation changed. Capture again.",
      u8"DAWの時計か遅延補正が変わりました。もう一度取り込んでください。" },
    { "The comparison stopped before it could be completed.", u8"比較は終わる前に止まりました。" },
};
}

Section blindSection() noexcept
{
    return { "blind", entries, sizeof (entries) / sizeof (entries[0]) };
}
}
