#include "HyphaJapaneseCatalog.h"

// PRE / POST Blind: its steps, the DAW and HYPHA instructions for each one, the answers, and every
// reason it can stop. It is a Preference Listening Trial, so the answers say which source is
// preferred, never which one is better.
namespace hypha::i18n::catalog
{
namespace
{
const Entry entries[] = {
    // The step bar and the purpose line (HyphaLocalBlindSteps.h, INV-S43).
    { "1  Capture", u8"1  取り込み" },
    { "2  Start", u8"2  開始" },
    { "3  Listen", u8"3  試聴" },
    { "4  Answer", u8"4  回答" },
    { "5  Result", u8"5  結果" },
    { "Hear the same 4 seconds of PRE and POST at matched level, without knowing which is "
      "which, and say which you prefer, if either.",
      u8"同じ4秒間のPREとPOSTを、音量を揃え、どちらがどちらか分からない状態で聴き比べます。"
      u8"好みがあれば、その方を答えます。" },
    // Steps.
    { "READY TO CAPTURE", u8"取り込み準備完了" },
    { "BEFORE CAPTURE", u8"取り込みの前に" },
    { "CAPTURING EXACT 4 SECOND RANGE", u8"同じ4秒間を取り込み中" },
    { "Keep playback running without seeking, looping, bypassing, or changing PDC.",
      u8"再生を続けてください。移動、ループ、バイパス、PDCの変更はしないでください。" },
    { "PREPARING COMPARISON", u8"比較を準備中" },
    { "The live signal remains unchanged while the fixed copies are checked.",
      u8"固定したコピーを確認する間も、今の音は変わりません。" },
    { "EXACT RANGE READY", u8"範囲の準備完了" },
    { "HYPHA: start Blind. DAW: play from before the captured range.",
      u8"HYPHA：Blindを開始します。DAW：取り込んだ範囲の少し前から再生してください。" },
    { "LOWER POST %1 dB & START", u8"POSTを%1 dB下げて開始" },
    { "Approve fixed POST attenuation and start Blind Compare",
      u8"POSTを一定量下げることを承認し、Blind Compareを開始します" },
    { "START BLIND", u8"Blindを開始" },
    { "Start the prepared comparison. PRE is matched to POST with fixed gain; DAW Solo and "
      "routing stay unchanged",
      u8"準備した比較を始めます。PREは固定のゲインでPOSTに揃えます。DAWのソロと経路は変わりません" },
    { "SOURCE 1 COMPLETE", u8"SOURCE 1 聴取完了" },
    { "SOURCE 2 READY", u8"SOURCE 2 準備完了" },
    { "WAITING FOR CAPTURED RANGE START", u8"範囲の始まりを待機中" },
    { "DAW: replay from before the captured range. No source selection is needed.",
      u8"DAW：取り込んだ範囲の少し前から、もう一度再生してください。ソースを選ぶ必要はありません。" },
    { "DAW: play from before the captured range to hear the full pass.",
      u8"DAW：取り込んだ範囲の少し前から再生して、1周を聴いてください。" },
    { "PASS COMPLETE", u8"1周完了" },
    { "SWITCHING TO SOURCE %1", u8"SOURCE %1に切り替え中" },
    { "LISTENING TO SOURCE %1", u8"SOURCE %1を再生中" },
    { "WAITING FOR AUDIBLE PLAYBACK", u8"音が出る再生を待っています" },
    { "Choose an answer to reveal, or replay a source if needed.",
      u8"回答を選ぶと答えを表示します。必要ならソースをもう一度再生できます。" },
    { "DAW: replay the captured range. The next source is selected automatically.",
      u8"DAW：取り込んだ範囲をもう一度再生してください。次のソースは自動で選ばれます。" },
    { "Listen to one complete pass of Source 1 and Source 2.",
      u8"Source 1とSource 2を、それぞれ1周ずつ最後まで聴いてください。" },
    { "%1. Select END when finished.", u8"%1。終わったら「終了」を選んでください。" },
    { ". Select END when finished.", u8"終わったら「終了」を選んでください。" },
    { "WAITING FOR LIVE OUTPUT", u8"今の音の出力を待機中" },
    { "RETURN TO LIVE", u8"今の音に戻す" },
    { "DAW: resume audio processing. Closes when Live is confirmed.",
      u8"DAW：音声処理を再開してください。今の音を確認できたら閉じます。" },
    { "Live level will rise by %1 dB.", u8"今の音のレベルが%1 dB上がります。" },
    { "Return to the unchanged live signal.", u8"変えていない今の音に戻ります。" },
    { "COMPARISON STOPPED", u8"比較を中止しました" },
    { "%1 Live +%2 dB.", u8"%1 今の音は+%2 dB戻ります。" },
    { "LIVE SIGNAL RESTORED", u8"今の音に戻りました" },
    { "The comparison is closed. Live output is restored.",
      u8"比較を閉じました。今の音の出力に戻りました。" },
    { "GAIN MATCH UNAVAILABLE", u8"Gain Matchを使えません" },
    { "COMPARISON NOT PREPARED", u8"比較を準備できません" },

    // Sources and answers.
    { "DONE", u8"完了" },
    { "PLAYING", u8"再生中" },
    { "NEXT", u8"次" },
    { "ANSWER: PREFER 1", u8"回答：1が好み" },
    { "ANSWER: PREFER 2", u8"回答：2が好み" },
    { "ANSWER: NO PREFERENCE", u8"回答：どちらでもない" },
    { "ANSWER: CANNOT TELL", u8"回答：区別できない" },
    { "NO PREF", u8"好みなし" },
    { "NO PREFERENCE", u8"どちらでもない" },
    { "CAN'T TELL", u8"区別できない" },
    { "CANNOT TELL", u8"区別できない" },
    { "BACK TO KEEP", u8"Keepに戻る" },
    { "CAPTURE AGAIN", u8"もう一度取り込む" },
    { "CAPTURE 4 S", u8"4秒を取り込む" },
    { "CLOSE", u8"閉じる" },
    { "Replay hidden source 1 (optional)", u8"隠れたソース1をもう一度再生します（任意）" },
    { "Replay hidden source 2 (optional)", u8"隠れたソース2をもう一度再生します（任意）" },
    { "Source 1 progress; selection is automatic", u8"ソース1の進み具合です。選択は自動です" },
    { "Source 2 progress; selection is automatic", u8"ソース2の進み具合です。選択は自動です" },
    { "Listen to hidden source 1", u8"隠れたソース1を聴きます" },
    { "Listen to hidden source 2", u8"隠れたソース2を聴きます" },
    { "Choose source 1 and reveal", u8"ソース1を選んで答えを表示します" },
    { "Choose source 2 and reveal", u8"ソース2を選んで答えを表示します" },
    { "Choose no preference and reveal", u8"「どちらでもない」を選んで答えを表示します" },
    { "Choose cannot tell apart and reveal", u8"「区別できない」を選んで答えを表示します" },
    { "Start the prepared comparison", u8"準備した比較を始めます" },
    { "Reveal the hidden source assignment", u8"隠れたソースの割り当てを表示します" },
    { "Capture one exact four second range", u8"同じ4秒間を取り込みます" },
    { "Resolve the capture requirement", u8"取り込みに必要な条件を整えます" },
    { "Gain Match mode for this comparison", u8"この比較のGain Matchのモード" },
    { "2MIX: continuous sections. TRACK / STEM: short or sparse events. Applies to this "
      "comparison.",
      u8"2MIX：途切れない音の区間。TRACK / STEM：短い音やまばらな音。この比較にだけ使います。" },
    { "Stop the comparison safely", u8"比較を安全に止めます" },
    { "Return explicitly to the live signal", u8"操作して今の音に戻ります" },
    { "Close Blind Compare", u8"Blind Compareを閉じます" },

    // Before a capture.
    { "DAW: play the section. HYPHA: capture 4 seconds.",
      u8"DAW：その区間を再生してください。HYPHA：4秒間を取り込みます。" },
    { "This format cannot start PRE / POST Blind.", u8"この形式ではPRE / POST Blindを始められません。" },
    { "Finish the current comparison and return to Live.",
      u8"今の比較を終えて、今の音に戻ってください。" },
    { "The previous capture is still releasing its resources.",
      u8"前の取り込みがまだ資源を解放しています。" },
    { "Choose the PRE to compare with this POST.", u8"このPOSTと比べるPREを選んでください。" },
    { "Finish the current Keep / Record before capturing.",
      u8"取り込む前に、今のKeep／Recordを終えてください。" },
    { "Finish Reference Blind and return to Live first.",
      u8"先にReferenceのBlindを終えて、今の音に戻ってください。" },
    { "The previous audio capture is still in use.", u8"前の音声の取り込みがまだ使われています。" },
    { "DAW: start playback, then capture the section.",
      u8"DAW：再生を始めてから、その区間を取り込んでください。" },
    { "DAW sample position or format is not available for capture.",
      u8"DAWの再生位置か形式を、取り込みに使えません。" },
    { "The measurement engine is not available.", u8"計測エンジンを使えません。" },
    { "Capture could not be admitted. Check the current pair and comparisons.",
      u8"取り込みを始められませんでした。今のペアと比較を確認してください。" },
    { "The capture request could not be sent. Try again after it is released.",
      u8"取り込みの要求を送れませんでした。解放されてから、もう一度試してください。" },
    { "Capture could not start.", u8"取り込みを開始できませんでした。" },

    // Why it stopped.
    { "The selected pair changed. Return to the live signal, then capture again.",
      u8"選んだペアが変わりました。今の音に戻ってから、もう一度取り込んでください。" },
    { "The exact range could not be scheduled. Keep playback running and try again.",
      u8"同じ範囲を予約できませんでした。再生を続けたまま、もう一度試してください。" },
    { "The exact PRE and POST range was not completed.",
      u8"PREとPOSTの同じ範囲を取り込みきれませんでした。" },
    { "Capture a section where both PRE and POST contain audible events.",
      u8"PREとPOSTの両方に音がある区間を取り込んでください。" },
    { "Capture a busier section. For short sounds, choose TRACK / STEM.",
      u8"音の多い区間を取り込んでください。短い音ならTRACK / STEMを選んでください。" },
    { "The comparison could not be prepared. Capture again.",
      u8"比較を準備できませんでした。もう一度取り込んでください。" },
    { "The prepared comparison could not be made available.",
      u8"準備した比較を使える状態にできませんでした。" },
    { "The channel layout or sample rate changed.", u8"チャンネル構成かサンプルレートが変わりました。" },
    { "Playback stopped, bypassed, or entered offline render.",
      u8"再生が止まったか、バイパスされたか、オフラインのレンダリングに入りました。" },
    { "The comparison ownership changed.", u8"比較を行う側が変わりました。" },
    { "Playback jumped outside the exact captured sequence.",
      u8"再生が取り込んだ範囲の外へ移動しました。" },
    { "Playback did not begin at the captured range start.",
      u8"再生が取り込んだ範囲の始まりから始まりませんでした。" },
    { "The host clock or delay compensation changed. Capture again.",
      u8"DAWの時計か遅延補正が変わりました。もう一度取り込んでください。" },
    { "The comparison stopped before it could be completed.", u8"比較は終わる前に止まりました。" },
};
}

Section blindSection() noexcept
{
    return { "blind", entries, sizeof (entries) / sizeof (entries[0]) };
}
}
