#include "HyphaJapaneseCatalog.h"

// REF: its status line, its actions, its help and the Kirin OS access panel. Most statuses join
// facts with " / ", and each fact is translated on its own (HyphaLanguage.cpp), so the entries
// here are mostly those facts. Kirin OS names (Reference, Version, Check, Check Preset, Cue, Work,
// Blind Compare) stay as Kirin OS writes them.
namespace hypha::i18n::catalog
{
namespace
{
const Entry entries[] = {
    // Status facts.
    { "A REMAINS LIVE", u8"Aは今の音のまま" },
    { "BLIND STOPPED", u8"Blindを中止" },
    { "A HELD %1 dB", u8"Aを%1 dBで保持中" },
    { "RETURN A EXPLICITLY", u8"Aは手動で戻す" },
    { "PAUSED", u8"一時停止" },
    { "PLAY TO RESUME BLIND", u8"再生でBlind再開" },
    { "PLAY WITHIN THE SONG", u8"曲の範囲内で再生" },
    { "WAITING FOR FIRST AUDIBLE BLOCK", u8"最初の音を待っています" },
    { "A LOWERED %1 dB", u8"Aを%1 dB下げ中" },
    { "RETURNS ON END", u8"終了時に戻る" },
    { "SOURCE IDENTITY HIDDEN", u8"ソースは伏せています" },
    { "REVEALED", u8"答え表示中" },
    { "%1 AUDITION", u8"%1を試聴中" },
    { "PRE DELTA PAUSED", u8"PRE差分は停止中" },
    { u8"PRE Δ PAUSED", u8"PREのΔは停止中" },
    { "REF REQUIRES KIRIN OS", u8"REFにはKirin OSが必要" },
    { "WAITING FOR KIRIN OS REFERENCE", u8"Kirin OSのReferenceを待機中" },
    { "READY", u8"準備完了" },
    { "PLAY A TO AUDITION", u8"Aを再生して試聴" },
    { "SAVED CHOICE UNAVAILABLE", u8"保存した選択は使えません" },
    { "CHOOSE AGAIN", u8"選び直して" },
    { "VERIFYING SOURCE", u8"ソースを確認中" },
    { "CHOOSE VERSION B", u8"BのVersionを選択" },
    { "PLAY A", u8"Aを再生" },
    { "ALIGNING VERSION B", u8"Bを位置合わせ中" },
    { "PLAY ANOTHER PASSAGE TO ALIGN B", u8"別の箇所を再生してBを合わせる" },
    { "CHOOSE A SOURCE IN KIRIN OS", u8"Kirin OSでソースを選択" },
    { "ENABLE A CHECK IN KIRIN OS", u8"Kirin OSでCheckを有効に" },
    { "SOURCE UNAVAILABLE", u8"ソースを使えません" },
    { "OPEN KIRIN OS", u8"Kirin OSを開く" },
    { "RECEIVING REFERENCE", u8"Referenceを受信中" },
    { "KIRIN OS PREPARING CHECK PRESET", u8"Kirin OSがCheck Presetを準備中" },
    { "CHECK PRESET READY", u8"Check Preset準備完了" },
    { "KIRIN OS NEEDS MORE TIME", u8"Kirin OSの準備待ち" },
    { "CHOOSE A REFERENCE IN KIRIN OS", u8"Kirin OSでReferenceを選択" },
    { "REFERENCE SOURCE NEEDS ATTENTION", u8"Referenceのソースを確認" },
    { "MEASURE THE REFERENCE SOURCE IN KIRIN OS", u8"Kirin OSでReferenceのソースを計測" },
    { "CHECK PRESET NOT REFRESHED", u8"Check Presetが未更新" },
    { "REFERENCE SETUP NEEDS ATTENTION", u8"Referenceの設定を確認" },
    { "KIRIN OS PREPARING REFERENCE", u8"Kirin OSがReferenceを準備中" },
    { "REFERENCE READY", u8"Reference準備完了" },
    { "REFERENCE NOT REFRESHED", u8"Referenceが未更新" },
    { "OPENING REFERENCE IN KIRIN OS", u8"Kirin OSでReferenceを開いています" },
    { "CONTINUE IN KIRIN OS", u8"Kirin OSで続行" },
    { "KIRIN OS OPENED THE REFERENCE LOCATION", u8"Kirin OSでReferenceの場所を開きました" },
    { "KIRIN OS OPENED SAFE REFERENCE SETTINGS", u8"Kirin OSでReferenceの設定を開きました" },
    { "REFERENCE ITEM IS NO LONGER AVAILABLE", u8"そのReferenceの項目はもうありません" },
    { "KIRIN OS DID NOT RESPOND", u8"Kirin OSが応答しません" },
    { "SAMPLE RATE %1 TO %2 kHz", u8"サンプルレート %1 → %2 kHz" },
    { "BLIND NEEDS HEADROOM", u8"Blindには余裕が必要" },
    { "A RETURNS +%1 dB ON END", u8"終了時にAは+%1 dB戻ります" },
    { "SOURCE CHANGED", u8"ソース変更" },
    { "PREPARE AGAIN IN KIRIN OS", u8"Kirin OSで準備し直す" },
    { "SOURCE COULD NOT BE OPENED", u8"ソースを開けませんでした" },
    { "VERIFY IN KIRIN OS", u8"Kirin OSで確認" },
    { "SOURCE FORMAT CHANGED", u8"ソース形式が変更" },
    { "SOURCE OR CUE CHANGED", u8"ソースかCueが変更" },
    { "CONTINUE WHEN READY", u8"準備できたら続行" },
    { "PREPARE", u8"要準備" },
    { "CONTENT ALIGNED", u8"内容で位置合わせ済" },
    { "ALIGNING", u8"位置合わせ中" },
    { "PROJECT TIMELINE", u8"プロジェクトの時間軸" },
    { "REFERENCE CUE", u8"ReferenceのCue" },
    { "BELOW RANGE", u8"範囲より下" },
    { "ABOVE RANGE", u8"範囲より上" },
    { "WITHIN RANGE", u8"範囲内" },
    { "CLICK AGAIN FOR OVERVIEW", u8"もう一度クリックで全体表示" },
    { "ORIGINAL LEVELS", u8"元のレベル" },
    { "A CHANGED", u8"Aが変化" },
    { "NO DATA", u8"データなし" },
    { "MATCH UNAVAILABLE", u8"Gain Match不可" },
    { "LOADING %1 AT PLAYHEAD", u8"再生位置で%1を読み込み中" },
    { "KEEP PLAYING", u8"再生を継続" },
    { "%1 SAMPLE RATE %2 TO %3 kHz", u8"%1のサンプルレート %2 → %3 kHz" },
    { "APPROVE %1 RATE", u8"%1の変換を承認" },
    { "APPROVE %1 %2 TO %3 kHz", u8"%1の%2 → %3 kHzを承認" },

    // Version Blind inside REF.
    { "SELECT 1 OR 2", u8"1か2を選択" },
    { "SWITCHING TO %1", u8"%1に切り替え中" },
    { "AUDIBLE SOURCE %1", u8"聴いているソース %1" },
    { "CONFIRMED", u8"確定" },
    { "PREFER %1", u8"%1が好み" },
    { "REVEAL WHEN READY", u8"準備できたら答えを表示" },
    { "NO COMPARISON SHOWN", u8"比較は非表示" },
    { "RETURN A +%1 dB", u8"Aを+%1 dB戻す" },
    { "END", u8"終了" },
    { "CHOOSE", u8"選ぶ" },
    { "REVEAL", u8"答えを表示" },
    { "Open Blind at 300%", u8"300%でBlindを開きます" },
    { "Approve B conversion", u8"Bの変換を承認" },
    { "Approve C conversion", u8"Cの変換を承認" },
    { "Verifying B source", u8"Bのソースを確認中" },
    { "Verifying C source", u8"Cのソースを確認中" },
    { "Loading B at the playhead", u8"再生位置でBを読み込み中" },
    { "Loading C at the playhead", u8"再生位置でCを読み込み中" },
    { "Approve rate conversion", u8"サンプルレート変換を承認" },
    { "Verifying source", u8"ソースを確認中" },
    { "Loading audio here; keep playing", u8"読込中・再生を継続" },
    { "Only the audition copy changes. A stays unchanged.",
      u8"試聴用コピーだけが変わります。Aは変わりません。" },
    { "The source is being checked. A stays live.",
      u8"ソースを確認中です。音はAのままです。" },
    { "Keep playing while audio loads.", u8"音声を読み込む間は再生を続けてください。" },
    { "Reveal both sources without recording a preference.",
      u8"好みを記録せず、両方のソースを表示します。" },
    { "Listen to both sources before revealing them.",
      u8"答えを表示する前に両方のソースを聴いてください。" },

    // Actions.
    { "RETRY PREPARATION", u8"準備をやり直す" },
    { "OPEN REFERENCE", u8"Referenceを開く" },
    { "CHOOSE SOURCE", u8"ソースを選ぶ" },
    { "MEASURE SOURCE", u8"ソースを計測" },
    { "TRY KIRIN OS AGAIN", u8"Kirin OSで再試行" },
    { "USE %1 TO %2 kHz", u8"%1 → %2 kHzで使う" },
    { "LOWER A %1 dB & START", u8"Aを%1 dB下げて開始" },
    { "PREPARE VISUALS", u8"表示を準備" },
    { "EDIT GENRE", u8"ジャンル編集" },
    { "Preparing B overview", u8"Bの全体表示を準備中" },

    // Selectors and buttons.
    { "Temporarily call a Check Preset received from Kirin OS.",
      u8"Kirin OSから受け取ったCheck Presetを一時的に呼び出します。" },
    { "Choose the registered Version for B. A stays the current DAW input.",
      u8"Bに使う登録済みのVersionを選びます。AはDAWの今の入力のままです。" },
    { "Choose Version", u8"Versionを選ぶ" },
    { "Temporarily call a Check received from Kirin OS.",
      u8"Kirin OSから受け取ったCheckを一時的に呼び出します。" },
    { "Replace B with a prepared past Version or Reference for this audition.",
      u8"この試聴だけ、Bを準備済みの過去のVersionかReferenceに置き換えます。" },
    { "Choose a prepared listening position for this audition.",
      u8"この試聴で使う、準備済みの聴く位置を選びます。" },
    { "Audition A", u8"Aを試聴" },
    { "Audition B", u8"Bを試聴" },
    { "Audition C Check", u8"CのCheckを試聴" },
    { "Start Version Blind", u8"Version Blindを開始" },
    { "Audition blind source 1", u8"Blindのソース1を試聴" },
    { "Audition blind source 2", u8"Blindのソース2を試聴" },
    { "Reveal blind sources", u8"Blindのソースを表示" },
    { "End Blind Compare", u8"Blind Compareを終了" },
    { "Return to the live DAW mix (A).", u8"DAWの今のミックス（A）に戻ります。" },
    { "Audition the Kirin OS prepared Reference (B).",
      u8"Kirin OSが準備したReference（B）を試聴します。" },
    { "Start a separate Version Blind trial. Check Preset settings and facts are hidden.",
      u8"別のVersion Blindを始めます。Check Presetの設定と計測値は隠れます。" },
    { "Audition source 1. Its identity remains hidden.",
      u8"ソース1を試聴します。どちらのソースかは隠れたままです。" },
    { "Audition source 2. Its identity remains hidden.",
      u8"ソース2を試聴します。どちらのソースかは隠れたままです。" },
    { "Reveal which source is A and which source is B.",
      u8"どちらがAで、どちらがBかを表示します。" },
    { "Approve %1 %2 to %3 kHz for the audition copy only. A stays unchanged.",
      u8"試聴用コピーの%1を%2 → %3 kHzに変換します。Aは変わりません。" },
    { "End Blind Compare and return to live A.", u8"Blind Compareを終了し、今の音のAに戻ります。" },
    { "Continue with the safe next action.", u8"次の安全な操作に進みます。" },
    { "Return the live A level after the interrupted Blind Compare.",
      u8"中断したBlind Compareの後で、今の音のAのレベルを戻します。" },
    { "Open this Balance Check in Kirin OS.", u8"このBalance CheckをKirin OSで開きます。" },
    { "Kirin OS connected", u8"Kirin OSに接続中" },
    { "Kirin OS offline / received presets available",
      u8"Kirin OSはオフラインです / 受け取ったプリセットは使えます" },
    { "Waiting for Kirin OS", u8"Kirin OSを待っています" },
    { "A and B comparison. Arrows move the view; Shift and arrows resize it; Home follows "
      "playback.",
      u8"AとBの比較です。矢印キーで表示を動かし、Shiftと矢印キーで幅を変え、Homeで再生位置に"
      u8"追従します。" },
    { "A and B comparison. Arrows move; Shift and arrows resize; Home follows playback.",
      u8"AとBの比較です。矢印キーで動かし、Shiftと矢印キーで幅を変え、Homeで再生位置に"
      u8"追従します。" },

    // The review workflow.
    { "Start or continue the latest review.", u8"最新のレビューを始めるか、続けます。" },
    { "Prepare the latest saved comparison. Audio stays on A.",
      u8"最後に保存した比較を準備します。音はAのままです。" },
    { "Prepare the previous review item. Audio stays on A.",
      u8"前のレビュー項目を準備します。音はAのままです。" },
    { "Mark this item checked and prepare the next item.",
      u8"この項目を確認済みにして、次の項目を準備します。" },
    { "Hold this item and prepare the next item.", u8"この項目を保留にして、次の項目を準備します。" },
    { "End this workflow and restore the normal Reference selection.",
      u8"このレビューを終え、通常のReferenceの選択に戻します。" },
    { "PREPARING", u8"準備中" },
    { "SAVING", u8"保存中" },
    { "CHANGED", u8"変更あり" },

    // The Kirin OS access panel and the REF information menu.
    { "Kirin OS Reference access", u8"Kirin OSのReference" },
    { "About Kirin OS / trial and purchase information", u8"Kirin OSについて / 試用と購入の情報" },
    { "Already own Kirin OS / connection help", u8"Kirin OSをお持ちの方 / 接続のヘルプ" },
    { "Recheck the local Kirin OS license", u8"このコンピュータのKirin OSのライセンスを確認し直します" },
    { "ABOUT KIRIN OS", u8"Kirin OSについて" },
    { "ALREADY OWN IT?", u8"お持ちの方" },
    { "RECHECK LICENSE", u8"ライセンス再確認" },
    { "BACK", u8"戻る" },
    { "WAITING FOR KIRIN OS", u8"Kirin OSを待機中" },
    { "Open Kirin OS.\nSaved Reference presets arrive automatically.",
      u8"Kirin OSを開いてください。\n保存したReferenceのプリセットは自動で届きます。" },
    { "License not confirmed. Open Kirin OS, then Recheck License.\nSaved Reference presets "
      "arrive automatically.",
      u8"ライセンスを確認できていません。Kirin OSを開いてから、ライセンスを再確認してください。\n"
      u8"保存したReferenceのプリセットは自動で届きます。" },
    { "Open Kirin OS, then Recheck License.\nSaved Reference presets arrive automatically.",
      u8"Kirin OSを開いてから、ライセンスを再確認してください。\n保存したReferenceのプリセットは"
      u8"自動で届きます。" },
    { "Compare audio registered in Kirin OS.\nAbout: product, trial and purchase information.",
      u8"Kirin OSに登録した音声と聴き比べます。\n「Kirin OSについて」：製品、試用、購入の情報です。" },
    { "Kirin OS / Product, trial and purchase", u8"Kirin OS / 製品、試用、購入" },
    { "About Kirin OS (English)", u8"Kirin OSについて（英語）" },
    { "Copy official URL (English)", u8"公式URLをコピー（英語）" },
    { "Copy official URL (Japanese)", u8"公式URLをコピー（日本語）" },
};
}

Section referenceSection() noexcept
{
    return { "reference", entries, sizeof (entries) / sizeof (entries[0]) };
}
}
