#include "HyphaJapaneseCatalog.h"

// The analysis pages: FREQ (Spectrum, PSB, Focus Trail), SHARP, LIVE, SPACE and DRUM. Their
// statuses, the notices a refused mode gives, and their hover help.
namespace hypha::i18n::catalog
{
namespace
{
const Entry entries[] = {
    // Shared analysis states.
    { "INACTIVE", u8"入力なし" },
    { "PREPARING ANALYSIS", u8"解析を準備中" },
    { "ANALYSIS DATA UNAVAILABLE", u8"解析データがありません" },
    { "ANALYSIS IN USE", u8"解析を使用中" },
    { "ANALYSIS SLOTS IN USE", u8"解析の枠を使用中" },
    { "PAIR PRE TO VIEW DIFFERENCE\nPOST SHARPNESS IS IN LIVE",
      u8"差分を見るにはPREとペアにしてください\nPOSTのシャープネスはLIVEにあります" },

    // FREQ help.
    { "M/S: show POST Mid and Side together. Stereo only.",
      u8"M/S：POSTのMidとSideを重ねて表示します。ステレオのみです。" },
    { "MID: analyze (L + R) / 2.", u8"MID：(L + R) / 2 を解析します。" },
    { "SIDE: analyze (L - R) / 2. Stereo only.", u8"SIDE：(L - R) / 2 を解析します。ステレオのみです。" },
    { "LR: analyze L and R separately, then average power.",
      u8"LR：LとRを別々に解析し、パワーを平均します。" },
    { "Select POST to show Mid and Side together.",
      u8"MidとSideを重ねて見るには、POSTを選んでください。" },
    { "M/S requires a stereo input.", u8"M/Sにはステレオの入力が必要です。" },
    { "POST Mid and Side at one frequency. Click to lock the readout.",
      u8"ひとつの周波数でのPOSTのMidとSideです。クリックで読み取りを固定します。" },
    { "Move to inspect frequency and Delta. Click to lock Focus Trail.",
      u8"動かすと周波数と差分を表示します。クリックでFocus Trailを固定します。" },
    { "POST Spectrum: current magnitude, six-second field, and rolling peak hold.",
      u8"POSTのスペクトラム：今のレベル、6秒間の履歴、ピークホールドです。" },
    { "~ means approximate frequency. Very low tones need a longer window to locate exactly.",
      u8"~ はおおよその周波数です。とても低い音の位置を正確に求めるには、長い窓が必要です。" },
    { "Delta: POST minus PRE on the left dB scale.", u8"Δ：POST − PREの差分です。左のdB目盛りで読みます。" },
    { "PRE: input spectrum on the right dBFS scale.",
      u8"PRE：入力のスペクトラムです。右のdBFS目盛りで読みます。" },
    { "POST: output spectrum on the right dBFS scale.",
      u8"POST：出力のスペクトラムです。右のdBFS目盛りで読みます。" },
    { "Clear the MARK reference.", u8"MARKの基準線を消します。" },
    { "MARK: freeze the current full-band Delta curve.",
      u8"MARK：今の全帯域の差分カーブを固定して残します。" },
    { "Release the frequency lock.", u8"周波数の固定を解除します。" },
    { "Focus Trail: six seconds of Delta at the locked frequency.",
      u8"Focus Trail：固定した周波数での6秒間の差分です。" },
    { "RAW: exact POST - PRE spectral difference",
      u8"RAW：同じ窓で測ったPOST − PREのスペクトラムの差" },
    { "SHAPE: spectral difference after same-window energy normalization",
      u8"SHAPE：同じ窓で全体のエネルギーをそろえてから求めたスペクトラムの差" },
    { u8"SHAPE — LOW ENERGY", u8"SHAPE — 低エネルギー" },
    { "PSB: perceptual share by Bark band", u8"PSB：Bark帯域ごとの知覚上の割合" },
    { "Spectrum: frequency level and difference", u8"スペクトラム：周波数ごとのレベルと差分" },
    { "Return to Spectrum", u8"スペクトラムに戻ります" },
    { "Show perceptual spectral balance", u8"知覚上の帯域バランスを表示します" },
    { "LR specific-loudness share", u8"LRの特定ラウドネスの割合" },
    { "FOCUS TRAIL  /  CLICK A BAND", u8"FOCUS TRAIL  /  帯域をクリック" },
    { "Analysis size: 100%", u8"解析の大きさ：100%" },
    { "Analysis size: 125%", u8"解析の大きさ：125%" },
    { "Analysis size: 150%", u8"解析の大きさ：150%" },
    { "Analysis size: 200%", u8"解析の大きさ：200%" },
    { "Analysis size: 300% inspection view", u8"解析の大きさ：300%（Inspection View）" },
    { "Show POST - PRE analysis", u8"POST − PREの解析を表示します" },
    { "Return to meters", u8"メーターに戻ります" },

    // A mode the page cannot take says why for a moment.
    { "M/S -- POST STEREO", u8"M/S：要POSTステレオ" },
    { "SIDE -- STEREO", u8"SIDE：ステレオのみ" },
    { "SIDE -- MONO", u8"SIDE：モノ不可" },
    { "MODE --", u8"使用不可" },
    { "MARK --", u8"MARK不可" },

    // PSB.
    { "PRE REQUIRED FOR DELTA", u8"差分にはPREが必要です" },
    { "PSB UNAVAILABLE", u8"PSB利用不可" },
    { "PSB WARMING", u8"PSBを準備中" },

    // SHARP and LIVE help.
    { "Sharpness Delta is POST minus PRE. Unit: acum (DIN 45692).",
      u8"シャープネスの差分（POST − PRE）です。単位：acum（DIN 45692）。" },
    { "LIVE shows absolute POST facts on independent fixed scales.",
      u8"LIVEは、POSTの絶対値をそれぞれ固定の目盛りで表示します。" },
    { "LUFS-M: 400 ms momentary loudness. Absolute POST value.",
      u8"LUFS-M：400 msのモーメンタリーラウドネスです。POSTの絶対値です。" },
    { "True Peak: highest inter-sample peak in 400 ms. Unit: dBTP.",
      u8"トゥルーピーク：400 msの間のサンプル間ピークの最大値です。単位：dBTP。" },
    { "Sharpness: high-frequency weighting. Unit: acum (DIN 45692).",
      u8"シャープネス：高域の重み付けです。単位：acum（DIN 45692）。" },

    // SPACE.
    { "MONO INPUT", u8"モノラル入力" },
    { "WARMING %1/30", u8"準備中 %1/30" },

    // DRUM: why a hit has no value, and the page's own states.
    { "NEXT HIT", u8"次の打音" },
    { "QUIET AFTER", u8"後が無音" },
    { "PRE ONLY", u8"PREのみ" },
    { "POST ONLY", u8"POSTのみ" },
    { "NO PAIR", u8"ペアなし" },
    { "NO HIT", u8"打音なし" },
    { "UNAVAILABLE", u8"利用不可" },
    { "WARMING UP", u8"準備中" },

    // DRUM BAND (B-1097, B-1098): what the engine stated for a hit in the band, the guidance
    // and the hover help.
    { "RINGING", u8"余韻あり" },
    { "NO SOUND", u8"音なし" },
    { "PRE NO SOUND", u8"PREに音なし" },
    { "POST NO SOUND", u8"POSTに音なし" },
    { "LONG TAIL", u8"余韻が長い" },
    { "NOT MEASURED", u8"未計測" },
    { "UPDATE PRE", u8"PREを更新" },
    // The short words of the narrowest cells (100% and the one-line readout).
    { "QUIET", u8"無音" },
    { "RING", u8"余韻" },
    { "NONE", u8"無音" },
    { "LONG", u8"長い" },
    { "UPDATE", u8"要更新" },
    { "MEASURING", u8"測定中" },
    { "PLAY TO MEASURE", u8"再生すると測ります" },
    { "PLAY TO MEASURE %1", u8"再生すると%1を測ります" },
    { "ALL: every hit measured on the whole signal, as DRUM always has. No audio is kept for the bands while ALL is chosen.",
      u8"ALL：これまでどおり、全帯域で打音を測ります。ALLの間は帯域のための音を保持しません。" },
    { "Octave band %1: %2. Each hit is measured in this band on PRE and POST once its ring-out is over; switching between bands measures the last 7 s again, even when stopped. Time resolution: one period, %3.",
      u8"%1のオクターブ帯域（%2）。PREとPOSTの各打音を、余韻が終わってからこの帯域で測ります。帯域を切り替えると、直近7秒を停止中でも測り直します。時間の細かさは1周期の%3です。" },
    { "This PRE predates bands and sends none: update PRE to compare the band. POST's own values are shown meanwhile.",
      u8"このPREは帯域に対応する前の版のため、帯域を送りません。PREを更新すると帯域を比べられます。それまではPOST自身の値を表示します。" },
    { "HEAD: the band envelope around the onset. The lines mark where PRE and POST rise through their peak - 20 dB; DELAY is the gap between them.",
      u8"HEAD：打音の前後の帯域包絡です。線はPREとPOSTがピーク − 20 dBを上向きに越えた時刻で、その差がDELAYです。" },
    { "TAIL: the band envelope over 300 ms. The marks show where PRE and POST fall to peak - 20 dB; REL is the time from the peak to that point.",
      u8"TAIL：300 msの帯域包絡です。印はPREとPOSTがピーク − 20 dBまで下がった時刻で、ピークからそこまでがRELです。" },
    { "DELAY: POST arrival minus PRE arrival in this band, ms. Arrival is where the envelope rises through its peak - 20 dB. RINGING: the previous hit still rings in this band, so the start cannot be timed.",
      u8"DELAY：この帯域でのPOSTの到達時刻 − PREの到達時刻（ms）です。到達時刻は包絡がピーク − 20 dBを上向きに越えた時刻です。余韻あり：前の打音がこの帯域でまだ鳴っていて、始まりを測れません。" },
    { "ATT: the rise from 10 % to 90 % of the band peak, ms. A rise shorter than the band's time resolution (one period) reads as an upper bound, such as <16 ms.",
      u8"ATT：帯域のピークの10 %から90 %までの立ち上がり時間（ms）です。帯域の時間の細かさ（1周期）より短いときは、<16 msのように上限で示します。" },
    { "REL: the fall from the band peak to peak - 20 dB, ms. >288 ms: still ringing where the measured tail ends. NEXT HIT: the next hit came first. LONG TAIL: both sides ring past the tail.",
      u8"REL：帯域のピークからピーク − 20 dBまで下がる時間（ms）です。>288 ms：測った尾の終わりでもまだ鳴っています。次の打音：次の打音が先に来ました。余韻が長い：両側とも尾を越えて鳴っています。" },
    { "LEVEL: the band's peak envelope level. POST - PRE in dB when paired, dBFS otherwise. When one side has no sound in the band, the difference reads as a bound, such as <-66 dB.",
      u8"LEVEL：帯域包絡のピークのレベルです。ペア時はPOST − PRE（dB）、それ以外はdBFSです。片側がこの帯域で音なしのときは、<-66 dBのように差を上限で示します。" },
    // DRUM band summary (2026-09-29): the recent hits that rise in the band, read in words.
    { "LATER", u8"遅れ" },
    { "EARLIER", u8"先行" },
    { "SLOWER", u8"ゆるやか" },
    { "FASTER", u8"急" },
    { "LONGER", u8"長い" },
    { "SHORTER", u8"短い" },
    { "LOUDER", u8"大きい" },
    { "QUIETER", u8"小さい" },
    { "SAME", u8"差なし" },
    { "WITHIN %1", u8"%1以内" },
    { "%1  LAST %2 HITS", u8"%1　直近%2打" },
    { "%1  LAST HIT", u8"%1　直近1打" },
    { "LAST %1 HITS", u8"直近%1打" },
    { "LAST HIT", u8"直近1打" },
    { "%1 HITS WITHOUT %2 LEFT OUT", u8"%2の音が無い%1打は除外" },
    { "1 HIT WITHOUT %1 LEFT OUT", u8"%1の音が無い1打は除外" },
    { "LATER %1 ms", u8"%1 ms遅れ" },
    { "EARLIER %1 ms", u8"%1 ms先行" },
    { "SLOWER %1 ms", u8"%1 msゆるやか" },
    { "FASTER %1 ms", u8"%1 ms急" },
    { "LONGER %1 ms", u8"%1 ms長い" },
    { "SHORTER %1 ms", u8"%1 ms短い" },
    { "LOUDER %1 dB", u8"%1 dB大きい" },
    { "QUIETER %1 dB", u8"%1 dB小さい" },
    { "POST %1 ms LATER", u8"POSTが%1 ms遅れ" },
    { "POST %1 ms EARLIER", u8"POSTが%1 ms先行" },
    { "ATTACK %1 ms SLOWER", u8"立ち上がりが%1 msゆるやか" },
    { "ATTACK %1 ms FASTER", u8"立ち上がりが%1 ms急" },
    { "TAIL %1 ms LONGER", u8"余韻が%1 ms長い" },
    { "TAIL %1 ms SHORTER", u8"余韻が%1 ms短い" },
    { "LEVEL %1 dB LOUDER", u8"音量が%1 dB大きい" },
    { "LEVEL %1 dB QUIETER", u8"音量が%1 dB小さい" },
    { "DELAY: SAME", u8"到達：差なし" },
    { "ATTACK: SAME", u8"立上り：差なし" },
    { "TAIL: SAME", u8"余韻：差なし" },
    { "LEVEL: SAME", u8"音量：差なし" },
    { "DELAY: RINGING", u8"到達：余韻あり" },
    { "ATTACK: RINGING", u8"立上り：余韻あり" },
    { "TAIL: NEXT HIT", u8"余韻：次の打音" },
    { "TAIL: LONG TAIL", u8"余韻：測定窓を越える" },
    { "DELAY: NO PAIR", u8"到達：ペアなし" },
    { "DELAY: UPDATE PRE", u8"到達：PREを更新" },
    { "- SMALLER / EARLIER", u8"- 小さい・早い" },
    { "LATER / LARGER +", u8"遅い・大きい +" },
    { "- SMALLER", u8"- 小さい" },
    { "LARGER +", u8"大きい +" },
    { "0 = SAME", u8"0 = 差なし" },
    { "POST VALUES", u8"POSTの値" },
    { "DELAY: POST arrival minus PRE arrival of each recent hit in this band, as dots; the bar is the median. The figure under it says how many hits lie on the median's side of zero.",
      u8"DELAY：この帯域での直近の各打音のPOSTの到達 − PREの到達を点で示し、棒が中央値です。下の数字は、中央値と同じ側にある打音の数です。" },
    { "ATT: the rise of each recent hit in this band, POST minus PRE, as dots; the bar is the median. Inside the shaded span (one period of the band) no difference can be told apart.",
      u8"ATT：この帯域での直近の各打音の立ち上がり（POST − PRE）を点で示し、棒が中央値です。影の範囲（帯域の1周期）の中では差を見分けられません。" },
    { "REL: the fall from the band peak to peak - 20 dB of each recent hit, POST minus PRE, as dots; the bar is the median.",
      u8"REL：直近の各打音の、帯域のピークからピーク − 20 dBまで下がる時間（POST − PRE）を点で示し、棒が中央値です。" },
    { "LEVEL: the band's peak level of each recent hit, POST minus PRE, as dots; the bar is the median.",
      u8"LEVEL：直近の各打音の帯域のピークレベル（POST − PRE）を点で示し、棒が中央値です。" },
    { "DELAY needs PRE: POST arrival minus PRE arrival.",
      u8"DELAYにはPREが必要です：POSTの到達 − PREの到達。" },
    { "ATT: POST's rise of each recent hit in this band, as dots; the bar is the median.",
      u8"ATT：この帯域での直近の各打音のPOSTの立ち上がりを点で示し、棒が中央値です。" },
    { "REL: POST's fall from the band peak to peak - 20 dB of each recent hit, as dots; the bar is the median.",
      u8"REL：直近の各打音の、POSTの帯域のピークからピーク − 20 dBまで下がる時間を点で示し、棒が中央値です。" },
    { "LEVEL: POST's band peak level of each recent hit, as dots; the bar is the median.",
      u8"LEVEL：直近の各打音のPOSTの帯域のピークレベルを点で示し、棒が中央値です。" },
    { "The recent hits that rise in this band, summed up: each lane's median and how many hits agree. Click a dot to see that hit; END or LIVE returns here.",
      u8"この帯域で音が立ち上がった直近の打音のまとめです。各段の中央値と、同じ向きの打音の数を示します。点をクリックするとその打音を表示し、ENDまたはLIVEでここに戻ります。" },
    { "Drum transient facts for TRACK/STEM; not a 2MIX onset detector.",
      u8"TRACK／STEMのドラムの打音ごとの計測値です。2MIXの立ち上がり検出ではありません。" },
};
}

Section analysisSection() noexcept
{
    return { "analysis", entries, sizeof (entries) / sizeof (entries[0]) };
}
}
