#include "HyphaJapaneseCatalog.h"

// REF の A／B／C／V（ABCV）で足した文。C の画面（H12）の曲・MATCH・同じ区間の見比べと、MATCH を
// やり直せなかったときの理由。CHECK SET・LOW 20-250 などの見出しと単位は英語のまま。
namespace hypha::i18n::catalog
{
namespace
{
const Entry entries[] = {
    { "NO SOURCE IN KIRIN OS", u8"Kirin OSに音源なし" },
    { "LEVEL NOT MATCHED", u8"音量未調整" },
    { "C Song", u8"Cの曲" },
    { "Choose the song C plays for this Check. A stays the current DAW input.",
      u8"このCheckでCが鳴らす曲を選びます。AはDAWの今の入力のままです。" },
    { "Match C to A again", u8"CをAにもう一度合わせる" },
    { "Match C to the latest A over the Cue's length again, and keep it fixed.",
      u8"Cueと同じ長さの直近のAにCをもう一度合わせ、固定します。" },
    { "Play C matched to the latest A over the Cue's length.", u8"Cueと同じ長さの直近のAに合わせてCを鳴らします。" },
    { "C is not playing. Press C to play it matched.", u8"Cは鳴っていません。Cを押すと合わせて鳴らします。" },
    { "This Check plays at its original level.", u8"このCheckは元の音量で鳴らします。" },
    { "Play A for the Cue length (up to 30 s), then MATCH again.", u8"Cueの長さ（最長30秒）だけAを再生してから、もう一度MATCHを押してください。" },
    { "This Check matches True Peak when C starts. Press A, then C.", u8"このCheckはCを鳴らすときにTrue Peakで合わせます。Aを押してからCを押してください。" },
    { "MATCH exceeds the safe level. The current gain is kept.", u8"MATCHが安全上限を超えます。今のgainを保ちます。" },
    { "PLAY A WITH V ALIGNED", u8"Vを位置合わせしてAを再生" },
    // H6：待ちが上限を超えたときの理由と直し方（「V: %1」の %1 にそのまま入る）。
    { "A LEVEL NOT MEASURED IN 10 S OF PLAY / PLAY A LONGER, THEN SELECT AGAIN",
      u8"再生10秒でAを測れません / Aを長めに再生して選び直す" },
    { "KIRIN OS IS NOT RESPONDING / OPEN KIRIN OS", u8"Kirin OSが応答しません / Kirin OSを開く" },
    { "SOURCE NOT VERIFIED IN 10 S / CHECK THE SOURCE IN KIRIN OS", u8"10秒で音源を確認できません / Kirin OSで確認" },
    { "AUDIO NOT LOADED IN 10 S / PLAY FROM ANOTHER POSITION", u8"10秒で読み込めません / 別の位置から再生" },
    { "NOT PREPARED IN 10 S / OPEN THE SOURCE IN KIRIN OS", u8"10秒で準備できません / Kirin OSで開く" },
    { "NO MATCH IN 30 S OF PLAY / CHOOSE THE VERSION AGAIN", u8"再生30秒で位置が合いません / Versionを選び直す" },
    { "V is measured over the same section as A while they are aligned",
      u8"位置合わせしているあいだ、VをAと同じ区間で測ります" },
    { "A LEVEL NOT MEASURED IN 35 S OF PLAY / PLAY A LONGER, THEN SELECT AGAIN",
      u8"再生35秒でAを測れません / Aを長めに再生して選び直す" },
    // 追従を MATCH から ±6 dB で止めたとき（live 比較の AUTO と同じ幅）。
    { "%1 FOLLOW STOPPED 6 DB FROM MATCH", u8"%1の追従はMATCHから6 dBで停止" },
    { "Level follow stopped 6 dB from the MATCH. The current gain is kept.",
      u8"音量の追従はMATCHから6 dBで停止。今のgainを保ちます。" },
    // Kirin OS のセット（sets.json）を読めなかったとき。
    { "B SET NOT READ / UPDATE KIRIN OS AND HYPHA", u8"Bセットを読めません / Kirin OSとHyphaを更新" },
    { "Some Kirin OS sets were not read. Update Kirin OS and Hypha.",
      u8"Kirin OSのセットの一部を読めませんでした。Kirin OSとHyphaを更新してください。" },
    // V のタブ（その Check の表示に合わせる）。
    { "V compares spectrum and balance. This Check is shown on C.",
      u8"Vはスペクトルとバランスを比べます。このCheckはCの画面で見ます。" },
    // C の画面の MATCH の横と Cue の凡例。
    { "MATCHED / C %1 dB", u8"MATCH済み / C %1 dB" },
    { "ON PLAY / C %1 dB", u8"鳴らすとき / C %1 dB" },
    { "A WAITING", u8"A待ち" },
    { "A LAST %1 S", u8"A直近%1秒" },
    { "A %1 / %2 S", u8"A %1 / %2秒" },
    // 2026-10-04：図の凡例の比べる側（Daisuke「A直近10秒 / Bサビ」）。B は鳴らす部分の時刻を添える。
    { "B CHORUS %1", u8"Bサビ %1" },
    { "B LOUDEST 30 S %1", u8"B最も大きい30秒 %1" },
    { "B CUE %1", u8"BのCue %1" },
    { "B CHORUS", u8"Bサビ" },
    { "B LOUDEST 30 S", u8"B最も大きい30秒" },
    { "B CUE", u8"BのCue" },
    { "B WHOLE", u8"B曲全体" },
    { "C CHORUS", u8"Cサビ" },
    { "C LOUDEST 30 S", u8"C最も大きい30秒" },
    { "C CUE", u8"CのCue" },
    { "C WHOLE", u8"C曲全体" },
    { "B SET RANGE", u8"Bセットの範囲" },  // B セットの曲の p10〜p90 の帯
    // Blauert の帯（HyphaReferenceBlauertZones.h）：300-400 Hz・3-4 kHz に対する 1 kHz 付近の高さを、A を主語に。
    { u8"1k vs 300-400·3-4k", u8"300-400·3-4kに対する1k" },
    // 比べる側との差は A を主語に言葉で（HyphaReferenceAComparison.h。2026-10-04 Daisuke が選んだ）。
    { "A %1 MORE", u8"Aが%1多い" },
    { "A %1 LESS", u8"Aが%1少ない" },
    { "A %1 HIGHER", u8"Aが%1高い" },
    { "A %1 LOWER", u8"Aが%1低い" },
    { "A %1 LARGER", u8"Aが%1大きい" },
    { "A %1 SMALLER", u8"Aが%1小さい" },
    { "A %1 LOUDER", u8"Aが%1大きい" },
    { "A %1 QUIETER", u8"Aが%1小さい" },
    { "A %1 WIDER", u8"Aが%1広い" },
    { "A %1 NARROWER", u8"Aが%1狭い" },
    { "A SAME AS %1", u8"Aは%1と同じ" },
    // 4 帯域の欄は見出し（CよりA（dB））が主語を言う（「SAME」は解析の画面と同じ「差なし」）。
    { "%1 MORE", u8"%1多い" },
    { "%1 LESS", u8"%1少ない" },
    { "A VS C (dB)", u8"CよりA（dB）" },
    { "A VS V (dB)", u8"VよりA（dB）" },
    // 指標の欄（INTEGRATED LOUDNESS・MAXIMUM TRUE PEAK、200% 以下の LUFS-I・MAX TP）の差の列。
    { "A VS %1  %2", u8"%1よりA %2" },
    { "A VS %1", u8"%1よりA" },
    { "LU LOUDER", u8"LU大きい" },
    { "LU QUIETER", u8"LU小さい" },
    { "dB HIGHER", u8"dB高い" },
    { "dB LOWER", u8"dB低い" },
    { "SAME SECTION %1 S", u8"同じ区間 %1秒" },
    // 範囲の帯（HyphaReferenceRangeStrips.cpp）の項目名と、V の時間の線の見出し（「CREST (TP/RMS) / OVER TIME」）。
    { "CREST (TP/RMS)", u8"クレスト (TP/RMS)" },
    { "LOUDNESS MOVEMENT (LUFS-S)", u8"音量の動き (LUFS-S)" },
    { "ONSET (RISE PER HOP)", u8"立ち上がり (区間ごと)" },
    { "ATTACK (PEAK - LUFS-M)", u8"アタック (ピーク − LUFS-M)" },
    { "OVER TIME", u8"時間の動き" },
    // Kirin OS の標準の名前（HyphaReferenceDisplayText.h が英語の名前にそろえる）。日本語の画面では Kirin OS の日本語名で出す。
    { u8"Mastering · tone, level, and dynamics", u8"Mastering｜音色・音量・ダイナミクス" },
    { u8"MIX · balance, position, and space", u8"MIX｜バランス・定位・空間" },
    { u8"Recording · tone, performance, and capture", u8"録音｜音色・演奏・収録状態" },
    { u8"Album context", u8"Album 全体との関係" },
    { u8"Arrangement · roles, density, and development", u8"編曲｜役割・密度・展開" },
    { u8"Energy curve", u8"曲中のエネルギー変化" },
    { u8"Performance dynamics", u8"演奏のダイナミクス" },
    { u8"Frequency space", u8"周波数帯域の使い方" },
    { u8"Hook placement", u8"聴かせどころの位置" },
    { u8"Low-volume balance", u8"小音量時のバランス" },
    { u8"Section difference", u8"セクション間の違い" },
    { u8"All stages · 5 essential checks", u8"全工程｜基本5項目" },
    { u8"All stages · 3 essential checks", u8"全工程｜基本3項目" },
    { u8"Pitch and timing", u8"音程とタイミング" },
    { u8"Genre context", u8"ジャンルとの関係" },
    { u8"Delivery context", u8"納品条件との関係" },
    { u8"Loudest 30 s", u8"最も大きい30秒" },
    { u8"Instrumentation and roles", u8"楽器編成と役割" },
    { u8"Kick and bass", u8"キックとベース" },
    { u8"Tonal balance", u8"音色のバランス" },
    { u8"Stereo and phase", u8"ステレオと位相" },
    { u8"Separation and bleed", u8"分離とかぶり" },
    { u8"Phase and microphones", u8"位相とマイク" },
    { u8"Low-end consistency", u8"低域の安定性" },
    { u8"Lead position", u8"主役の位置" },
    { u8"Production stage", u8"制作段階" },
    { u8"Chorus candidate", u8"サビ候補" },
    { u8"High end", u8"高域" },
    { "%1 DB UNDER A (PEAK LIMIT)", u8"Aより%1 dB小さい（ピーク上限）" },
    // 耳で聴き比べる Check（V と C の画面。Kirin OS の「この項目は耳で聴き比べます」と同じ言い方）。
    { "Compared by listening. Hypha shows no result it has not measured. Press A and %1 to switch at the same level.",
      u8"この項目は耳で聴き比べます。Hyphaは測っていない結果を出しません。Aと%1を押して、同じ音量で切り替えてください。" },  // V の Check のタブの凡例（A と V の色は線の見本で示す）
    // K13b：Kirin OS の準備の状態（B の一覧の短い語と、状態の行の「理由 / 直し方」）。
    { "NOT FOUND", u8"見つからない" },
    { "CHECKING", u8"確認中" },
    { "%1 AHEAD", u8"前に%1曲" },
    { "KIRIN OS CANNOT FIND THE FILE / IT RETRIES ONCE SOON", u8"Kirin OSがファイルを確かめられません / まもなく再試行" },
    { "KIRIN OS CANNOT FIND THE FILE / RETRY IN KIRIN OS", u8"Kirin OSがファイルを確かめられません / Kirin OSで再試行" },
    { "KIRIN OS IS CHECKING THE FILE", u8"Kirin OSがファイルを確かめています" },
    { "KIRIN OS IS MEASURING THE SONG", u8"Kirin OSが曲を測っています" },
    { "KIRIN OS WAITS FOR ANOTHER MEASUREMENT", u8"Kirin OSはほかの測定を待っています" },
    { "KIRIN OS PREPARES THIS SONG NEXT", u8"Kirin OSが次にこの曲を準備します" },
    { "KIRIN OS PREPARES 1 SONG FIRST", u8"Kirin OSが先に1曲を準備しています" },
    { "KIRIN OS PREPARES %1 SONGS FIRST", u8"Kirin OSが先に%1曲を準備しています" },
    // H15：Kirin OS の中の「Hypha ではこう見える」（描画の道具）。
    { "PREVIEW / DAW INPUT NOT AVAILABLE", u8"プレビュー / DAWの入力はありません" },
    { "KIRIN OS PREVIEW", u8"Kirin OSのプレビュー" },
    // 2026-10-03（R-12）：上限超えの MATCH は、承認して A を下げて合わせる。
    { "%1 NEEDS A %2 DB LOWER", u8"%1はAを%2 dB下げると合う" },
    { "LOWER A TO MATCH", u8"Aを下げて合わせる" },
    { "LOWER A %1 DB & PLAY %2", u8"Aを%1 dB下げて%2を鳴らす" },
    { "A LOWERED %1 DB", u8"Aを%1 dB下げ中" },
    { "%1 needs A %2 dB lower to match. Press LOWER A.", u8"%1はAを%2 dB下げると合います。「Aを下げて…」を押してください。" },
    { "A was not lowered. Press the role again.", u8"Aは下げていません。もう一度押してください。" },
    { "A lowered %1 dB to match: A got louder after the offer.", u8"合わせるためにAを%1 dB下げました（承認の後にAが大きくなりました）。" },
    { "PRE / POST LISTEN is using POST. End it or press RETURN, then press the role again.",
      u8"PRE / POST LISTENがPOSTを使っています。終了するかRETURNを押してから、もう一度押してください。" },

    // 300% の B・C・V で項目を指したときの下の行の説明（HyphaReferenceHelpText.h。2026-10-04 Daisuke「下の行に出す」）。
    { "Bars: p10 to p90 of each window, the mark is the median. A gold, the compared side cyan.",
      u8"帯は各窓のp10〜p90、縦線は中央値。Aは金、比べる側は水色。" },
    { "Crest: how far peaks rise above the average (true peak over RMS), moment by moment.",
      u8"クレスト：瞬間ごとのピーク（TP）と平均（RMS）の差。ピークの立ち方。" },
    { "Loudness movement: how far the 3-second loudness swings around its median.",
      u8"音量の動き：3秒ごとの音量（LUFS-S）が中央値のまわりで上下する幅。" },
    { "Momentary loudness every 0.4 s, with the compared side at the level it plays at.",
      u8"0.4秒ごとの音量（LUFS-M）の分布。比べる側は鳴らす音量で並べる。" },
    { "Width: side against mid, up to 150%. Shows how wide the stereo image is.",
      u8"幅：Mid（中央）に対するSide（左右の差）の大きさ。広がりを見る。" },
    { "Correlation: how alike left and right move. +1 the same, 0 unrelated, -1 opposite.",
      u8"相関：左右がどれだけ同じ動きか。+1は同じ、0は無関係、−1は逆向き。" },
    { "Peak of each moment (dBFS), with the compared side at the level it plays at.",
      u8"瞬間ごとのピーク（dBFS）。比べる側は鳴らす音量に合わせて並べる。" },
    { "RMS of each moment (dBFS), the body of the sound, with the compared side at its playing level.",
      u8"瞬間ごとのRMS（dBFS）。音の芯の大きさ。比べる側は鳴らす音量で並べる。" },
    { "Onset: how sharply the level rises from the moment before. Shows the attacks.",
      u8"立ち上がり：前の瞬間からの音量の上がり方。アタックの強さを見る。" },
    { "Attack: how far each moment's peak stands above its loudness (LUFS-M); limiting lowers it.",
      u8"アタック：ピークがLUFS-Mからどれだけ突き出るか。詰めると小さくなる。" },
    { "The first fact over the last 30 seconds: A gold, V cyan, scaled to the lines.",
      u8"最初の項目の直近30秒の動き。Aは金、Vは水色。縦軸は線の値の範囲。" },
    { "Spectrum of C's Cue and the same length of recent A, with C at the level it plays at.",
      u8"CのCueと、同じ長さのAの直近のスペクトル。Cは鳴らす音量に合わせる。" },
    { "Spectrum of A and V over the same aligned section, with V at the level it plays at.",
      u8"位置合わせで対応したAとVの同じ区間のスペクトル。Vは鳴らす音量で。" },
    { "Balance: A's last 10 seconds, the chosen song and the B set's range, at B's level.",
      u8"Aの直近10秒、選んだ曲、Bセットの範囲（p10〜p90）。Bは鳴らす音量で。" },
    { "Blauert's bands: A's 1 kHz against 300-400 Hz and 3-4 kHz, bands tied to sensed distance.",
      u8"Blauertの帯：300-400・3-4 kHzに対する1 kHzの高さ。距離感に関わる。" },
    { "Four bands: how much more or less A has than C in each band, after matching level.",
      u8"4帯域：音量をそろえたCより、Aが各帯域でどれだけ多いか少ないか。" },
    { "Four bands: how much more or less A has than V in each band, over the same section.",
      u8"4帯域：同じ区間のVより、Aが各帯域でどれだけ多いか少ないか。" },
    { "Integrated loudness of A's recent window and of C, and how A compares with C.",
      u8"Aの直近の窓とCの統合ラウドネス（LUFS-I）と、CよりAの差。" },
    { "Highest true peak of A and of C at the level C plays at, and how A compares.",
      u8"AとCの最大トゥルーピーク（Cは鳴らす音量で）と、CよりAの差。" },
    { "Where C's Cue sits in the song and its loop. The line is C's playing position.",
      u8"曲の中のCのCueの位置とループ。線はCの再生位置。" },
    { "The gain C plays at: matched to A's recent window, or the gain it plays at now.",
      u8"Cを鳴らすgain。Aの直近の窓に合わせた値（鳴っていれば今の値）。" },
    { "Checks of this CHECK SET from Kirin OS. A tab changes C's Check and keeps the song.",
      u8"このCHECKセットのCheck。タブで曲はそのままCのCheckを替える。" },
    { "WHOLE shows the whole song; the other tabs compare A and V over the same section.",
      u8"WHOLEは曲全体。ほかのタブは同じ区間のAとVを比べる。" },
    { "The whole song: A above V, peak outside and RMS inside. Select a region to compare.",
      u8"曲全体：上がA、下がV。外側がピーク、内側がRMS。範囲を選ぶと比べる。" },
    { "Songs of the B set: the LUFS-I of each Cue and the gain MATCH would play it at.",
      u8"Bセットの曲：各曲のCueのLUFS-Iと、MATCHで鳴らすgain。" },
};
}

Section referenceAbcvSection() noexcept
{
    return { "reference abcv", entries, sizeof (entries) / sizeof (entries[0]) };
}
}
