#!/usr/bin/env node
import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const THIS_FILE = fileURLToPath(import.meta.url);
const DEFAULT_ROOT = path.resolve(path.dirname(THIS_FILE), '..');
const DEFAULT_ALLOWLIST = path.join(
  DEFAULT_ROOT,
  'scripts',
  'public_history_b_allowlist.tsv',
);
const FULL_SHA = /^[0-9a-f]{40}$/;
const SEMVER_TAG = /^v\d+\.\d+\.\d+$/;

function git(root, args, options = {}) {
  return execFileSync('git', args, {
    cwd: root,
    encoding: 'utf8',
    ...options,
  });
}

export function canonicalBLabel(subject) {
  const match = subject.match(/^\[B-(\d+)\](?:\s|$)/);
  if (!match) return null;
  return `B-${match[1].padStart(3, '0')}`;
}

export function parseReachableCommits(raw) {
  const fields = raw.split('\0');
  if (fields.at(-1) === '') fields.pop();
  if (fields.length % 2 !== 0) throw new Error('git log returned an incomplete commit record');
  const commits = [];
  for (let index = 0; index < fields.length; index += 2) {
    const sha = fields[index];
    if (!FULL_SHA.test(sha)) throw new Error(`git log returned an invalid full SHA: ${sha}`);
    commits.push({ sha, subject: fields[index + 1] });
  }
  return commits;
}

export function duplicateBGroups(commits) {
  const groups = new Map();
  for (const commit of commits) {
    const label = canonicalBLabel(commit.subject);
    if (!label) continue;
    if (!groups.has(label)) groups.set(label, new Set());
    groups.get(label).add(commit.sha);
  }
  return new Map([...groups].filter(([, shas]) => shas.size > 1));
}

function compareLabels(left, right) {
  const numeric = Number(left.slice(2)) - Number(right.slice(2));
  return numeric || left.localeCompare(right);
}

export function renderAllowlist(groups) {
  const lines = [
    '# Generated by: node scripts/check_public_history.mjs --write-allowlist --tip HEAD',
    '# Canonical leading B label<TAB>full commit SHA; do not edit by hand.',
  ];
  for (const label of [...groups.keys()].sort(compareLabels)) {
    for (const sha of [...groups.get(label)].sort()) lines.push(`${label}\t${sha}`);
  }
  return `${lines.join('\n')}\n`;
}

export function parseAllowlist(source) {
  const groups = new Map();
  for (const [index, line] of source.split(/\r?\n/).entries()) {
    if (line === '' || line.startsWith('#')) continue;
    const fields = line.split('\t');
    if (fields.length !== 2) throw new Error(`allowlist line ${index + 1} must have two TSV fields`);
    const [label, sha] = fields;
    if (!/^B-\d{3,}$/.test(label)) {
      throw new Error(`allowlist line ${index + 1} has a noncanonical B label: ${label}`);
    }
    if (!FULL_SHA.test(sha)) {
      throw new Error(`allowlist line ${index + 1} has an invalid full SHA: ${sha}`);
    }
    if (!groups.has(label)) groups.set(label, new Set());
    if (groups.get(label).has(sha)) {
      throw new Error(`allowlist line ${index + 1} repeats ${label} ${sha}`);
    }
    groups.get(label).add(sha);
  }
  return groups;
}

function setDifference(left, right) {
  return [...left].filter((value) => !right.has(value)).sort();
}

export function duplicateAllowlistErrors(commits, source) {
  const actual = duplicateBGroups(commits);
  const allowed = parseAllowlist(source);
  const errors = [];
  for (const label of [...actual.keys()].sort(compareLabels)) {
    if (!allowed.has(label)) {
      errors.push(`unapproved duplicate ${label}: ${[...actual.get(label)].sort().join(', ')}`);
      continue;
    }
    const added = setDifference(actual.get(label), allowed.get(label));
    const missing = setDifference(allowed.get(label), actual.get(label));
    if (added.length > 0) errors.push(`${label} has unapproved SHA(s): ${added.join(', ')}`);
    if (missing.length > 0) errors.push(`${label} lost approved SHA(s): ${missing.join(', ')}`);
  }
  for (const label of [...allowed.keys()].sort(compareLabels)) {
    if (!actual.has(label)) errors.push(`stale duplicate allowlist group: ${label}`);
  }
  if (source !== renderAllowlist(actual)) {
    errors.push('duplicate allowlist is not the exact deterministic rendering of reachable history');
  }
  return errors;
}

export function unreachableSemverTags(tags, isAncestor) {
  return tags.filter((tag) => SEMVER_TAG.test(tag) && !isAncestor(tag));
}

function parseArgs(argv) {
  const options = {
    root: DEFAULT_ROOT,
    tip: 'HEAD',
    allowlist: DEFAULT_ALLOWLIST,
    writeAllowlist: false,
  };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--repo') options.root = path.resolve(argv[++index] || '');
    else if (arg === '--tip') options.tip = argv[++index] || '';
    else if (arg === '--allowlist') options.allowlist = path.resolve(argv[++index] || '');
    else if (arg === '--write-allowlist') options.writeAllowlist = true;
    else throw new Error(`unknown option: ${arg}`);
  }
  if (!options.tip) throw new Error('--tip requires a revision');
  if (options.root !== DEFAULT_ROOT && options.allowlist === DEFAULT_ALLOWLIST) {
    options.allowlist = path.join(options.root, 'scripts', 'public_history_b_allowlist.tsv');
  }
  return options;
}

function isAncestor(root, ancestor, tip) {
  const result = spawnSync('git', ['merge-base', '--is-ancestor', ancestor, tip], {
    cwd: root,
    encoding: 'utf8',
  });
  if (result.status === 0) return true;
  if (result.status === 1) return false;
  throw new Error(result.stderr.trim() || `git merge-base failed for ${ancestor}`);
}

export function checkRepository(options) {
  const tip = git(options.root, ['rev-parse', '--verify', `${options.tip}^{commit}`]).trim();
  const commits = parseReachableCommits(
    git(options.root, ['log', '-z', '--format=%H%x00%s', tip]),
  );
  const duplicates = duplicateBGroups(commits);
  if (options.writeAllowlist) {
    fs.writeFileSync(options.allowlist, renderAllowlist(duplicates));
  }
  const allowlist = fs.readFileSync(options.allowlist, 'utf8');
  const errors = duplicateAllowlistErrors(commits, allowlist);
  const tags = git(options.root, ['tag', '--list']).split(/\r?\n/).filter(Boolean);
  const publicTags = tags.filter((tag) => SEMVER_TAG.test(tag));
  if (publicTags.length === 0) errors.push('no public SemVer tags were found');
  for (const tag of unreachableSemverTags(
    tags,
    (candidate) => isAncestor(options.root, candidate, tip),
  )) {
    errors.push(`public SemVer tag is not reachable from candidate main ${tip}: ${tag}`);
  }
  if (errors.length > 0) throw new Error(errors.join('\n'));
  return { tip, duplicateCount: duplicates.size, publicTagCount: publicTags.length };
}

function main() {
  const result = checkRepository(parseArgs(process.argv.slice(2)));
  console.log(
    `public history: PASS (${result.duplicateCount} approved duplicate B labels; `
      + `${result.publicTagCount} public SemVer tags reachable from ${result.tip})`,
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === THIS_FILE) {
  try {
    main();
  } catch (error) {
    console.error(`public history: FAIL\n${error.message}`);
    process.exitCode = 1;
  }
}
