//! External SuperFlux controls used only to audit the ATTACK candidate implementation.
//!
//! These contracts intentionally do not call or configure the product fixed-scale analyzer. They
//! reproduce named literature/source settings closely enough to make a later golden comparison
//! auditable, while remaining structurally ineligible for candidate ranking.

use sha2::{Digest, Sha256};

pub const SUPERFLUX_REFERENCE_CONTRACT_VERSION: &str = "kirin-superflux-reference-v1";
pub const PAPER_2013_SOURCE_URL: &str =
    "https://phenicx.upf.edu/system/files/publications/Boeck_DAFx-13.pdf";
pub const PAPER_2013_SOURCE_SHA256: &str =
    "313b9767900fee8c8063ba032a34f2090624a402f4eef1d00713bea61a1f8fb1";
pub const CPJKU_1_03_SOURCE_REVISION: &str = "0a85f898af69188324b649a4c640052a5443078e";
pub const CPJKU_1_03_SOURCE_URL: &str = "https://raw.githubusercontent.com/CPJKU/SuperFlux/0a85f898af69188324b649a4c640052a5443078e/SuperFlux.py";
pub const CPJKU_1_03_SOURCE_SHA256: &str =
    "c41059aa8f15b8a6ef70345b0a9696b3edf2d73bbe3c77a056d13ed7d615b75b";
/// SHA-256 of the little-endian `u32` bin points generated by the pinned CPJKU source.
pub const CPJKU_1_03_BIN_GOLDEN_SHA256: &str =
    "721fb9f9b5cb417ca10d361d4cc47cff4f1fdf1b4bdeeb0cea620100a072acc0";
pub const PAPER_2013_ONLINE_DEFINITION_SHA256: &str =
    "20618c61143d82497bcd17795375d24f351238ee1681538d00fac440677f4e55";
pub const CPJKU_1_03_ONLINE_DEFINITION_SHA256: &str =
    "f15132c7b9127fb251fa6aaaa9627546f1aa3f9f9c9f630d1892d887268c8829";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceId {
    Paper2013Online,
    Cpjku103Online,
}

impl SuperFluxReferenceId {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Paper2013Online => "paper_2013_online",
            Self::Cpjku103Online => "cpjku_1_03_online",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceDelta {
    DatasetSweptNoSingleValue,
    FixedMilliLogMagnitude(u32),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceWindow {
    NumpySymmetricHann,
}

impl SuperFluxReferenceWindow {
    const fn hash_tag(self) -> &'static str {
        match self {
            Self::NumpySymmetricHann => "symmetric-hann-n-minus-one-numpy-hanning",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceBinRounding {
    NumpyTiesToEven,
}

impl SuperFluxReferenceBinRounding {
    const fn hash_tag(self) -> &'static str {
        match self {
            Self::NumpyTiesToEven => "numpy-round-ties-to-even",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceBandReduction {
    Sum,
}

impl SuperFluxReferenceBandReduction {
    const fn hash_tag(self) -> &'static str {
        match self {
            Self::Sum => "odf-band-sum",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceMagnitudeCompression {
    Log10OnePlus,
}

impl SuperFluxReferenceMagnitudeCompression {
    const fn hash_tag(self) -> &'static str {
        match self {
            Self::Log10OnePlus => "filter-linear-magnitude-then-log10-a-plus-one",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceCombineProvenance {
    PaperDeclaredThirtyMilliseconds,
    CpjkuDocumentedThirtyMillisecondsLiteralCodeThirtyMicroseconds,
}

impl SuperFluxReferenceCombineProvenance {
    const fn hash_tag(self) -> &'static str {
        match self {
            Self::PaperDeclaredThirtyMilliseconds => "paper-declared-thirty-milliseconds",
            Self::CpjkuDocumentedThirtyMillisecondsLiteralCodeThirtyMicroseconds => {
                "cpjku-documented-thirty-milliseconds-literal-code-thirty-microseconds"
            }
        }
    }
}

impl SuperFluxReferenceDelta {
    const fn hash_tag(self) -> &'static str {
        match self {
            Self::DatasetSweptNoSingleValue => "dataset-swept-no-single-value",
            Self::FixedMilliLogMagnitude(_) => "fixed-milli-log-magnitude",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SuperFluxReferenceContract {
    pub id: SuperFluxReferenceId,
    pub parameter_source_url: &'static str,
    pub parameter_source_sha256: &'static str,
    pub numerical_source_url: &'static str,
    pub numerical_source_revision: &'static str,
    pub numerical_source_sha256: &'static str,
    pub sample_rate_hz: u32,
    pub frame_size_samples: u32,
    pub fft_bins: u32,
    pub frame_rate_fps: u32,
    pub hop_numerator_samples: u32,
    pub hop_denominator_frames: u32,
    pub window: SuperFluxReferenceWindow,
    pub bands_per_octave: u32,
    pub bin_rounding: SuperFluxReferenceBinRounding,
    pub frequency_min_millihz: u32,
    pub frequency_max_millihz: u32,
    pub reported_band_count: Option<u32>,
    pub magnitude_compression: SuperFluxReferenceMagnitudeCompression,
    pub spectral_lag_frames: u32,
    pub maximum_filter_radius: u32,
    pub maximum_filter_width: u32,
    pub band_reduction: SuperFluxReferenceBandReduction,
    pub pre_max_ms: u32,
    pub pre_avg_ms: u32,
    pub declared_post_max_ms: u32,
    pub declared_post_avg_ms: u32,
    pub effective_post_max_ms: u32,
    pub effective_post_avg_ms: u32,
    /// The documented 0.03-second input, normalized to an integer physical unit.
    pub combine_declared_input_micros: u32,
    /// A literal divisor applied by the named implementation (`1_000` in CPJKU 1.03).
    pub combine_implementation_divisor: u32,
    pub combine_provenance: SuperFluxReferenceCombineProvenance,
    pub delta: SuperFluxReferenceDelta,
}

impl SuperFluxReferenceContract {
    pub fn definition_hash(self) -> [u8; 32] {
        let mut hasher = Sha256::new();
        let reported_band_count_tag = if self.reported_band_count.is_some() {
            "reported-band-count-some"
        } else {
            "reported-band-count-none"
        };
        for field in [
            SUPERFLUX_REFERENCE_CONTRACT_VERSION,
            self.id.as_str(),
            self.parameter_source_url,
            self.parameter_source_sha256,
            self.numerical_source_url,
            self.numerical_source_revision,
            self.numerical_source_sha256,
            "external-validation-only-ranking-ineligible",
            "mono-arithmetic-mean-downmix",
            "integer-pcm-window-divided-by-dtype-max-float-unscaled",
            "online-right-aligned-python-int-truncated-floating-hop",
            self.window.hash_tag(),
            "complex-fft-first-n-over-two-bins-nyquist-excluded",
            "linear-magnitude-no-one-sided-or-window-energy-compensation",
            "a4-440-repeated-multiply-log-centers-one-corner-each-side",
            self.bin_rounding.hash_tag(),
            "unique-ascending-bin-points",
            "discard-bin-greater-than-or-equal-to-num-fft-bins",
            "triangles-start-inclusive-stop-exclusive-height-one",
            "triangle-area-not-normalized",
            reported_band_count_tag,
            self.magnitude_compression.hash_tag(),
            "past-frame-three-band-maximum-half-wave",
            self.band_reduction.hash_tag(),
            "scipy-constant-padding-inclusive-effective-peak-widths",
            "zero-delay",
            self.combine_provenance.hash_tag(),
            self.delta.hash_tag(),
        ] {
            hasher.update(field.as_bytes());
            hasher.update([0]);
        }
        for value in [
            self.sample_rate_hz,
            self.frame_size_samples,
            self.fft_bins,
            self.frame_rate_fps,
            self.hop_numerator_samples,
            self.hop_denominator_frames,
            self.bands_per_octave,
            self.frequency_min_millihz,
            self.frequency_max_millihz,
            self.reported_band_count.unwrap_or(0),
            self.spectral_lag_frames,
            self.maximum_filter_radius,
            self.maximum_filter_width,
            self.pre_max_ms,
            self.pre_avg_ms,
            self.declared_post_max_ms,
            self.declared_post_avg_ms,
            self.effective_post_max_ms,
            self.effective_post_avg_ms,
            self.combine_declared_input_micros,
            self.combine_implementation_divisor,
        ] {
            hasher.update(value.to_le_bytes());
        }
        if let SuperFluxReferenceDelta::FixedMilliLogMagnitude(value) = self.delta {
            hasher.update(value.to_le_bytes());
        }
        hasher.finalize().into()
    }

    pub fn definition_hex(self) -> String {
        hex::encode(self.definition_hash())
    }

    pub const fn pre_max_frames(self) -> u32 {
        self.frame_rate_fps * self.pre_max_ms / 1_000
    }

    pub const fn pre_avg_frames(self) -> u32 {
        self.frame_rate_fps * self.pre_avg_ms / 1_000
    }

    pub const fn effective_post_max_frames(self) -> u32 {
        self.frame_rate_fps * self.effective_post_max_ms / 1_000
    }

    pub const fn effective_post_avg_frames(self) -> u32 {
        self.frame_rate_fps * self.effective_post_avg_ms / 1_000
    }

    pub const fn effective_combine_micros(self) -> Option<u32> {
        self.combine_declared_input_micros
            .checked_div(self.combine_implementation_divisor)
    }
}

pub const PAPER_2013_ONLINE: SuperFluxReferenceContract = SuperFluxReferenceContract {
    id: SuperFluxReferenceId::Paper2013Online,
    parameter_source_url: PAPER_2013_SOURCE_URL,
    parameter_source_sha256: PAPER_2013_SOURCE_SHA256,
    numerical_source_url: CPJKU_1_03_SOURCE_URL,
    numerical_source_revision: CPJKU_1_03_SOURCE_REVISION,
    numerical_source_sha256: CPJKU_1_03_SOURCE_SHA256,
    sample_rate_hz: 44_100,
    frame_size_samples: 2_048,
    fft_bins: 1_024,
    frame_rate_fps: 200,
    hop_numerator_samples: 44_100,
    hop_denominator_frames: 200,
    window: SuperFluxReferenceWindow::NumpySymmetricHann,
    bands_per_octave: 24,
    bin_rounding: SuperFluxReferenceBinRounding::NumpyTiesToEven,
    frequency_min_millihz: 27_500,
    frequency_max_millihz: 16_000_000,
    reported_band_count: Some(138),
    magnitude_compression: SuperFluxReferenceMagnitudeCompression::Log10OnePlus,
    spectral_lag_frames: 2,
    maximum_filter_radius: 1,
    maximum_filter_width: 3,
    band_reduction: SuperFluxReferenceBandReduction::Sum,
    pre_max_ms: 30,
    pre_avg_ms: 100,
    declared_post_max_ms: 30,
    declared_post_avg_ms: 70,
    effective_post_max_ms: 0,
    effective_post_avg_ms: 0,
    combine_declared_input_micros: 30_000,
    combine_implementation_divisor: 1,
    combine_provenance: SuperFluxReferenceCombineProvenance::PaperDeclaredThirtyMilliseconds,
    delta: SuperFluxReferenceDelta::DatasetSweptNoSingleValue,
};

pub const CPJKU_1_03_ONLINE: SuperFluxReferenceContract = SuperFluxReferenceContract {
    id: SuperFluxReferenceId::Cpjku103Online,
    parameter_source_url: CPJKU_1_03_SOURCE_URL,
    parameter_source_sha256: CPJKU_1_03_SOURCE_SHA256,
    numerical_source_url: CPJKU_1_03_SOURCE_URL,
    numerical_source_revision: CPJKU_1_03_SOURCE_REVISION,
    numerical_source_sha256: CPJKU_1_03_SOURCE_SHA256,
    sample_rate_hz: 44_100,
    frame_size_samples: 2_048,
    fft_bins: 1_024,
    frame_rate_fps: 200,
    hop_numerator_samples: 44_100,
    hop_denominator_frames: 200,
    window: SuperFluxReferenceWindow::NumpySymmetricHann,
    bands_per_octave: 24,
    bin_rounding: SuperFluxReferenceBinRounding::NumpyTiesToEven,
    frequency_min_millihz: 30_000,
    frequency_max_millihz: 17_000_000,
    reported_band_count: None,
    magnitude_compression: SuperFluxReferenceMagnitudeCompression::Log10OnePlus,
    spectral_lag_frames: 2,
    maximum_filter_radius: 1,
    maximum_filter_width: 3,
    band_reduction: SuperFluxReferenceBandReduction::Sum,
    pre_max_ms: 10,
    pre_avg_ms: 150,
    declared_post_max_ms: 50,
    declared_post_avg_ms: 0,
    effective_post_max_ms: 0,
    effective_post_avg_ms: 0,
    combine_declared_input_micros: 30_000,
    combine_implementation_divisor: 1_000,
    combine_provenance:
        SuperFluxReferenceCombineProvenance::CpjkuDocumentedThirtyMillisecondsLiteralCodeThirtyMicroseconds,
    delta: SuperFluxReferenceDelta::FixedMilliLogMagnitude(1_100),
};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceLayoutStatus {
    VerifiedAgainstCpjku103BinGolden,
    PaperReported138ButCpjkuNumericsRealize139,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceTraceStatus {
    PendingNoOfficialAudioActivationGolden,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuperFluxReferenceUse {
    ExternalValidationOnlyRankingIneligible,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SuperFluxReferenceReceipt {
    pub id: SuperFluxReferenceId,
    pub definition_hash: [u8; 32],
    pub use_contract: SuperFluxReferenceUse,
    pub realized_unique_bin_points: usize,
    pub realized_band_count: usize,
    pub bin_layout_hash: [u8; 32],
    pub layout_status: SuperFluxReferenceLayoutStatus,
    pub trace_status: SuperFluxReferenceTraceStatus,
}

impl SuperFluxReferenceReceipt {
    pub const fn ranking_eligible(&self) -> bool {
        false
    }
}

pub fn build_superflux_reference_receipt(
    contract: SuperFluxReferenceContract,
) -> Result<SuperFluxReferenceReceipt, &'static str> {
    let definition_hash = contract.definition_hash();
    let expected_definition_hash = match contract.id {
        SuperFluxReferenceId::Paper2013Online => PAPER_2013_ONLINE_DEFINITION_SHA256,
        SuperFluxReferenceId::Cpjku103Online => CPJKU_1_03_ONLINE_DEFINITION_SHA256,
    };
    if hex::encode(definition_hash) != expected_definition_hash {
        return Err("SuperFlux named reference contract mismatch");
    }
    let bins = cpjku_filter_bins(contract)?;
    let bin_layout_hash = hash_bins(&bins);
    let layout_status = match contract.id {
        SuperFluxReferenceId::Paper2013Online => {
            if contract.reported_band_count != Some(138) || bins.len() - 2 != 139 {
                return Err("paper SuperFlux band-count discrepancy changed");
            }
            SuperFluxReferenceLayoutStatus::PaperReported138ButCpjkuNumericsRealize139
        }
        SuperFluxReferenceId::Cpjku103Online => {
            if bins.len() - 2 != 141 || hex::encode(bin_layout_hash) != CPJKU_1_03_BIN_GOLDEN_SHA256
            {
                return Err("CPJKU SuperFlux bin golden mismatch");
            }
            SuperFluxReferenceLayoutStatus::VerifiedAgainstCpjku103BinGolden
        }
    };
    Ok(SuperFluxReferenceReceipt {
        id: contract.id,
        definition_hash,
        use_contract: SuperFluxReferenceUse::ExternalValidationOnlyRankingIneligible,
        realized_unique_bin_points: bins.len(),
        realized_band_count: bins.len() - 2,
        bin_layout_hash,
        layout_status,
        trace_status: SuperFluxReferenceTraceStatus::PendingNoOfficialAudioActivationGolden,
    })
}

fn cpjku_filter_bins(contract: SuperFluxReferenceContract) -> Result<Vec<u32>, &'static str> {
    if contract.fft_bins < 3
        || contract.bands_per_octave == 0
        || contract.frequency_min_millihz == 0
        || contract.frequency_max_millihz <= contract.frequency_min_millihz
    {
        return Err("invalid SuperFlux reference filter parameters");
    }
    let fmin = contract.frequency_min_millihz as f64 / 1_000.0;
    let fmax =
        (contract.frequency_max_millihz as f64 / 1_000.0).min(contract.sample_rate_hz as f64 / 2.0);
    let factor = 2.0_f64.powf(1.0 / contract.bands_per_octave as f64);
    let mut frequencies = vec![440.0];
    let mut frequency = 440.0;
    while frequency <= fmax {
        frequency *= factor;
        frequencies.push(frequency);
    }
    frequency = 440.0;
    while frequency >= fmin {
        frequency /= factor;
        frequencies.push(frequency);
    }
    frequencies.sort_by(f64::total_cmp);
    let hz_per_bin = (contract.sample_rate_hz as f64 / 2.0) / contract.fft_bins as f64;
    let mut bins = Vec::with_capacity(frequencies.len());
    for frequency in frequencies {
        let bin = numpy_round_ties_even(frequency / hz_per_bin);
        if bin < contract.fft_bins && bins.last() != Some(&bin) {
            bins.push(bin);
        }
    }
    if bins.len() < 5 {
        return Err("SuperFlux reference filter has fewer than three bands");
    }
    Ok(bins)
}

fn numpy_round_ties_even(value: f64) -> u32 {
    let lower = value.floor();
    let fraction = value - lower;
    if fraction < 0.5 || (fraction == 0.5 && (lower as u64 & 1) == 0) {
        lower as u32
    } else {
        lower as u32 + 1
    }
}

fn hash_bins(bins: &[u32]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    for bin in bins {
        hasher.update(bin.to_le_bytes());
    }
    hasher.finalize().into()
}

#[cfg(test)]
#[path = "transient_superflux_reference_tests.rs"]
mod tests;
